### ISSUE TITLE
[BUG] - Unknown element <.nextui-dropdown-button> in collection.

### ISSUE THREAD

**Issue by Konixy** [nextui-org/nextui#1072]
### Describe the bug

When using <Dropdown.Button> it display the following error:
```
Error: Unknown element <.nextui-dropdown-button> in collection.
```
![image](https://user-images.githubusercontent.com/66780340/225337785-cdacc1be-e37e-4854-a803-6a07bdfacfdd.png)

### Your Example Website or App

https://codesandbox.io/p/sandbox/musing-ishizaka-95gues?welcome=true&file=%2Fpages%2Findex.jsx

### Steps to Reproduce the Bug or Issue

Go to [the codesandbox](https://codesandbox.io/p/sandbox/musing-ishizaka-95gues?welcome=true&file=%2Fpages%2Findex.jsx) and just click in the dropdown

### Expected behavior

expected the dropdown will open

### Operating System Version

Windows 11

### Browser

Opera

**Comment by nooikko** [comment]
Issue:
When using `Dropdown.Button` as a child of `Dropdown.Selection` or `Dropdown.Menu` an error is thrown stating `Error: Unknown element <.nextui-dropdown-button> in collection.`

Solution:
`Dropdown.Button` is not made to be a child of `Dropdown.Selection` or `Dropdown.Menu`. As shown in the [documentation](https://nextui.org/docs/components/dropdown#anatomy) it is made to be a top-level trigger to opening the menu. Instead, `Dropdown.Item` should be used a child of `Dropdown.Selection`. 

Follow Up Concerns:
In the above code provided, if you switch to `Dropdown.Item` it will give an error about `Link` not receiving an href. This is due to the fact that the code is attempting to use the `as` prop to pass in `Link` but `Dropdown.Item`'s types aren't extended by the passed component. As a result, it would most likely be best to avoid this style of utilization.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/dropdown
