### ISSUE TITLE
Add the ability to change <Input /> background color

### ISSUE THREAD

**Issue by devpikachu** [nextui-org/nextui#119]
**Is your iteration request related to a problem?**
Add the ability to change `<Input />` background color.

**Describe the solution you'd like**
Currently, the `<Input />` background, on light mode, is set to `palette.accents_2`, and on dark mode, to `palette.accents_1`. This works great when overlayed on a card on light mode, but on dark mode, both the card and the input take on `palette.accents_1` as a background color, making them blend together.

Ideally, the input should pick either `palette.background` on dark mode, or `palette.accents_2` in both cases, to preserve color animation on theme change, however, a quick workaround for this would be the ability to provide the background color as a prop to the `<Input />` component. This is currently not possible, as it only accepts `SimpleColors` passed to the `color` attribute.

**Additional context**

Light Mode:
![image](https://user-images.githubusercontent.com/30475873/141335049-e61ca6ea-435b-4e0f-8056-1648fdcb49ed.png)

Dark Mode:
![image](https://user-images.githubusercontent.com/30475873/141335096-abca7517-f1fd-4e50-944f-464fa507f90e.png)

**Comment by jrgarciadev** [comment]
Hey @devpikachu I'm glad to say that due to NextUI styles engine was totally migrated from `styled-jsx` to `stitches` you can use `css` prop, `styled` function or even style the `Input` component with you preferred style library, you can see de detailed documentation about how to override styles [here](https://nextui.org/docs/theme/override-styles)
