### ISSUE TITLE
[BUG] - You're importing a component that needs useEffect

### ISSUE THREAD

**Issue by QuesoCaliente** [nextui-org/nextui#1390]
### NextUI Version

2.0.18

### Describe the bug

I tried to use the chip component in a server component and got the following error

![image](https://github.com/nextui-org/nextui/assets/43506340/32995985-663b-4078-bb80-b0d22d149153)

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/43506340/39c39730-7ad1-4f90-94af-318cabcac6f9)

### Operating System Version

Windows

### Browser

Chrome

**Comment by WolverStones** [comment]
You need import Components directly like import {Avatar, AvatarGroup, AvatarIcon} from "@nextui-org/avatar"; not import {Avatar, AvatarGroup, AvatarIcon} from "@nextui-org/react";

**Comment by jrgarciadev** [comment]
Hey @QuesoCaliente import the `Chip` component from its package.

`import {Chip} from "@nextui-org/chip` (remember to install it first)

The chip component already includes the `use client;` directive since it has client hooks (which are not supported on RSC)

Some NextUI components as the `Kbd`, `Skeleton`, `Spinner` and others can be completely rendered on the server (don't need the `use client;` directive), you will find that those components have this tag in the docs:

![CleanShot 2023-08-13 at 21 26 33](https://github.com/nextui-org/nextui/assets/30373425/cd826b6a-c132-4e31-b470-d48e8b79f521)

**Comment by QuesoCaliente** [comment]
> Hey @QuesoCaliente import the `Chip` component from its package.
> 
> `import {Chip} from "@nextui-org/chip` (remember to install it first)
> 
> The chip component already includes the `use client;` directive since it has client hooks (which are not supported on RSC)
> 
> Some NextUI components as the `Kbd`, `Skeleton`, `Spinner` and others can be completely rendered on the server (don't need the `use client;` directive), you will find that those components have this tag in the docs:
> 
> ![CleanShot 2023-08-13 at 21 26 33](https://user-images.githubusercontent.com/30373425/260335267-cd826b6a-c132-4e31-b470-d48e8b79f521.png)

I am installing the complete nextui package following steps 1 2 and 3 according to the website and I am getting the error that I am showing on the screen, even without importing any nextui component

**Comment by jrgarciadev** [comment]
Did you follow the app directory steps? @QuesoCaliente  https://nextui.org/docs/frameworks/nextjs#app-directory-setup, when using the app directory you need to use individual imports, the main package `@nextui-org/react` does not include the `use client;` directive because not all exported components need it.

![CleanShot 2023-08-13 at 21 45 19](https://github.com/nextui-org/nextui/assets/30373425/42dc4978-2a2b-4f75-a7e4-e54c534561e1)

**Comment by QuesoCaliente** [comment]
> Did you follow the app directory steps? @QuesoCaliente https://nextui.org/docs/frameworks/nextjs#app-directory-setup, when using the app directory you need to use individual imports, the main package `@nextui-org/react` does not include the `use client;` directive because not all exported components need it.
> 
> ![CleanShot 2023-08-13 at 21 45 19](https://user-images.githubusercontent.com/30373425/260336119-42dc4978-2a2b-4f75-a7e4-e54c534561e1.png)

that was the problem, it's solved, thanks 😁

**Comment by Key5n** [comment]
> Did you follow the app directory steps? @QuesoCaliente https://nextui.org/docs/frameworks/nextjs#app-directory-setup, when using the app directory you need to use individual imports, the main package `@nextui-org/react` does not include the `use client;` directive because not all exported components need it.
> 
> ![CleanShot 2023-08-13 at 21 45 19](https://user-images.githubusercontent.com/30373425/260336119-42dc4978-2a2b-4f75-a7e4-e54c534561e1.png)

With no configuration, completion on quick fix on VSCode imports those components from '@nextui-org/react', not from '@nextui-org/button' for example.
This is very bothering since I have to manually import it.
Do you have useful tips to solve this problem?

**Comment by jrgarciadev** [comment]
Hey @WolverStones you can only install individual components, not the whole library (@nextui-org/react), check the individual installation guide: https://nextui.org/docs/guide/installation#individual-installation

So VsCode will recommend you import the component from the individual package instead of importing it from the main one.

Next.js doesn't support this `export * from 'nextui-component'` (at least at build time without transpilation) that's also what stops us from using `use client;` on top of the main file in addition to that, not all components are client components.

Another solution is to create your own file that exports the NextUI components check this file: https://github.com/nextui-org/nextui/blob/main/packages/core/react/src/index.ts (you'll see the "use client;" on top because is how we use it in the docs) but that directive is deleted prebuild time.
