### ISSUE TITLE
[BUG] - Kbd NextJS Error with Text Content

### ISSUE THREAD

**Issue by Tuan2002** [nextui-org/nextui#1419]
### NextUI Version

2.0.22

### Describe the bug

Error when I checking device to display key shortcut

### Steps to Reproduce the Bug or Issue

1. install "react-device-detect" via npm `npm i react-device-detect`
2. Import Kbd Component
3. import osName from react-device-detect
4. Check device to display key

### Expected behavior

It still working on the development env, but I can't run next build to production

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/64023863/4d5034fc-01fd-42ea-bf7e-fe22d3fe21a4)
<img width="669" alt="Screen Shot 2023-08-17 at 16 04 24" src="https://github.com/nextui-org/nextui/assets/64023863/9b18acb5-51cc-486b-bd10-ea5fb109cba3">

### Operating System Version

macOS

### Browser

Chrome

**Comment by Tuan2002** [comment]
This is my temp solution, but I not sure it work on other devices. So, I would like a depth fix for it
![image](https://github.com/nextui-org/nextui/assets/64023863/08b04b18-73ff-4af5-9b0d-b5be8ba8cb8c)

**Comment by jrgarciadev** [comment]
Hey you will have this issue with any component not only with the NextUI `Kbd`, because the device / os name is calculated at runtime so you have to implement a `mounted` strategy to only display the command when the component mounts.


You can take this part of the documentation as inspiration:https://github.com/nextui-org/nextui/blob/main/apps/docs/components/navbar.tsx#L73-L75
