### ISSUE TITLE
[BUG] -  RSC doesn't work with import .... from '@nextui-org/react'

### ISSUE THREAD

**Issue by ImRLopezAG** [nextui-org/nextui#1450]
### NextUI Version

2.0.22

### Describe the bug

When i try to use a nextui component from RSC and I import with **@nextui-org/react** it throws me the error i should use **useEffect**  with the 'use client' directives, to solve this i have to import the component from its own file.

RSC - Error
![image](https://github.com/nextui-org/nextui/assets/88790737/138f100b-f588-4349-b2d4-f1349601472b)
![image](https://github.com/nextui-org/nextui/assets/88790737/d85388cb-740e-4c92-8adc-f75c7b494afa)

RSC - All Ok
![image](https://github.com/nextui-org/nextui/assets/88790737/f1688cd9-8c5f-411a-a943-ef988a8d00f5)

but imagine that we want to import more than 2 components like card, button, tooltip, user in the same file and we use something like this to don't have a lot of imports in our file

![image](https://github.com/nextui-org/nextui/assets/88790737/909113f0-6fac-4800-8296-ae7338a2f4d2)

i think it's good idea to add directory which works with the RSC like

![image](https://github.com/nextui-org/nextui/assets/88790737/67fa389e-bedc-4fd5-b36d-3932a08135ed)

or make that directory works with RSC by default

### Steps to Reproduce the Bug or Issue

1. import components from main
2. use in a RSC

### Expected behavior

As a user, I'm expecting it works with RSC but I'm seeing that i have to use the 'use client directive' to it works

### Operating System Version

Windows

### Browser

Edge

**Comment by jrgarciadev** [comment]
Hey @ImRLopezAG yes that's expected behaviour, the main package `@nextui-org/react` doesn't include the `use client;` tag because not all exported components are client components, when using Next.js with App directory you need to import the components separately.

Please refer to the docs: https://nextui.org/docs/frameworks/nextjs#use-nextui-components

![CleanShot 2023-08-20 at 16 41 58](https://github.com/nextui-org/nextui/assets/30373425/f4cc1542-57d8-4b33-93f2-961f8fb5a13f)

You'll find that the server components have this tag on top:

![CleanShot 2023-08-20 at 16 44 32](https://github.com/nextui-org/nextui/assets/30373425/9f5aa778-934f-4807-870a-ecb68009d0d9)

It means that those components can be directly imported from `@nextui-org/react` without having to put `use client;` on top of your file.
