### ISSUE TITLE
[BUG] - Table with stripped and color bug when using selection mode

### ISSUE THREAD

**Issue by szbphoto** [nextui-org/nextui#1602]
### NextUI Version

2.1.12

### Describe the bug

When I use the Table componenet, set the table to stripped and then add a color="primary" then in the selection the stripped ones not color correctly
![image](https://github.com/nextui-org/nextui/assets/26623099/cbb23a90-c129-4cd1-825f-075b1cdd38a4)

### Steps to Reproduce the Bug or Issue

1. Add a Table component
2. Add selectionMode="multiple"
3. Add selectionBehavior="toggle"
4. Add color={"primary"}
5. Add isStriped

And you are done

### Expected behavior

I expected that the stripped ones also get the correct color just like the not stripped ones

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/26623099/9d73d429-c744-4c28-b270-5a9ef3854af1)

### Operating System Version

Windows

### Browser

Chrome

**Comment by iPachDev** [comment]
the last release (2.1.12) does not resolve the issue :/, thanks

<img width="1009" alt="Captura de pantalla 2023-09-13 a la(s) 15 21 29" src="https://github.com/nextui-org/nextui/assets/1483440/01a218e4-fef8-4dc0-b694-bf548758bb61">

**Comment by gabosdk** [comment]
Same Here, I notice that bug with isStriped active.

**Comment by stosh15x** [comment]
The root cause is that the striped classes are being added after the selection classes.

`<td tabindex="0" data-key="3232created" role="gridcell" class="py-2 px-3 relative align-middle whitespace-normal text-small font-normal [&amp;>*]:z-1 [&amp;>*]:relative outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 before:content-[''] before:absolute before:z-0 before:inset-0 before:opacity-0 data-[selected=true]:before:opacity-100 group-data-[disabled=true]:text-foreground-300 before:bg-primary/20 data-[selected=true]:text-primary group-data-[odd=true]:before:bg-default-100 group-data-[odd=true]:before:opacity-100 group-aria-[selected=false]:group-data-[hover=true]:before:bg-default-100 group-aria-[selected=false]:group-data-[hover=true]:before:opacity-70 first:before:rounded-l-lg last:before:rounded-r-lg" data-selected="true"><div class="flex flex-col"><p class="">test</p></div></td>`

`.group[data-odd=true] .group-data-\[odd\=true\]\:before\:bg-default-100::before {
    content: var(--tw-content);
    --tw-bg-opacity: 1;
    background-color: hsl(var(--nextui-default-100) / var(--nextui-default-100-opacity, var(--tw-bg-opacity)));
}`

`.before\:bg-primary\/20::before {
    content: var(--tw-content);
    background-color: hsl(var(--nextui-primary) / 0.2);
}`

if there was a data-[selected=true]:before:bg-primary added then it would take priority

**Comment by stosh15x** [comment]
or change this line from 
`data-[selected=true]:text-primary group-data-[odd=true]:before:bg-default-100`

to
`data-[selected=true]:text-primary group-data-[odd=true]:before:bg-primary`

**Comment by sjoerdvanBommel** [comment]
I'll take a look at this one as my first issue :)

**Comment by visak2614** [comment]
I'll take a look at this one as my first issue :)

**Comment by wingkwong** [comment]
@visak2614 please check out other issues instead. There is a linked PR already, which means someone may already fix it.

**Comment by sorcerb** [comment]
I’m hitting this bug now in @heroui/react@2.8.0-beta.7 with Tailwind v4. Could this be a regression?

**Comment by Kismet333** [comment]
I just upgraded to version 2.8.8 and I can verify this bug still exists
