### ISSUE TITLE
[Textarea] Unable to stretch the height of the textarea to fill the entire container.

### ISSUE THREAD

**Issue by Innei** [nextui-org/nextui#1706]
### NextUI Version

2.1.13

### Describe the bug

```
 <Textarea
              ref={ref}
              className="w-full"
              classNames={{
                inputWrapper: '!h-[calc(100vh-10rem)] max-h-[600px]',
                input: '!h-full',
              }}
              style={{
                height: '100% !important',
              }}
/>
```
I use the above code to fill the container height of the textarea, but the height of the textarea is controlled by autosize, and I cannot maximize its height through any props.

### Steps to Reproduce the Bug or Issue

1. Code like above or other.

### Expected behavior

Textarea should be full the whole wrapper.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/41265413/2038660e-c5a0-4380-bb28-ce8269a9c610

### Operating System Version

macOS

### Browser

Chrome

**Comment by 5war00p** [comment]
You cannot give min height to the textarea as the default behaviour of the textarea is to scroll inside the input field. Instead of specifying height, use `minRows` prop that fits up the parent div.

On another note, you can use `fullWidth` prop to fill the textarea as same as it's parent's width.

PS: the default height of the text area will be `[line height] * [no.of rows specified]`

**Comment by jrgarciadev** [comment]
You can disable the autosize by using `disableAutosize`, it will render a normal Textarea without the height sizes calculations.

https://codesandbox.io/p/sandbox/intelligent-hertz-cjwm3k?file=%2FApp.jsx%3A14%2C17&utm_medium=sandpack
