### ISSUE TITLE
[BUG] - Input label animation breaks down with react-hook-form defaultValues

### ISSUE THREAD

**Issue by FullmetalBober** [nextui-org/nextui#1718]
### NextUI Version

2.1.13

### Describe the bug

```
'use client';

import { TTestSchema } from '@/schemas/test';
import { useForm } from 'react-hook-form';
import { Input } from '@nextui-org/input';

export default function FormTest() {
  const { register } = useForm<TTestSchema>({ defaultValues: { title: 'TEST' } });

  return (
    <form>
      <Input {...register('title')} label='Title' variant='bordered' />
    </form>
  );
}
```

### Your Example Website or App

https://github.com/RAK-MANIAK/logical-creativity/blob/feat/new-test-form/src/components/test/FormTest.tsx

### Steps to Reproduce the Bug or Issue

1. Pass fefault value by react-hook-form
2. Check your input label

### Expected behavior

I expected to see a label above the text

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/106311891/bec20fca-e0df-44a2-9bc8-8e45edaf4632)

### Operating System Version

Windows

### Browser

Chrome

**Comment by WorldOfMaze** [comment]
I am having the same issue without `reack-hook-form` but only when the `defaultValue` property is a variable.  Everything works fine when using string literals.  Also, once the field has been edited, the label behaves properly.  Typical code that exhibits the problem is 

`<Input defaultValue={selectedItem?.id} label="ID" />`

while

 `<Input defaultValue="A record ID" label="ID" />`

works fine.

I suspect that `reack-hook-form` supplies a variable for `defaultValue` which leads me to believe that this is the same issue.

**Comment by RAK-MANIAK** [comment]
> I am having the same issue without `reack-hook-form` but only when the `defaultValue` property is a variable. Everything works fine when using string literals. Also, once the field has been edited, the label behaves properly. Typical code that exhibits the problem is
> 
> `<Input defaultValue={selectedItem?.id} label="ID" />`
> 
> while
> 
> `<Input defaultValue="A record ID" label="ID" />`
> 
> works fine.
> 
> Also, if I use the `value` property instead of `defaultValue`, all is well but I then get an error from React:
> 
> `Warning: A component is changing an uncontrolled input to be controlled`
> 
> I suspect that `reack-hook-form` supplies a variable for `defaultValue` which leads me to believe that this is the same issue.

I think the problem is not defaultValue gets the variable or string literals. In your example, _selectedItem?.id_ in the first render value is possibly _undefiend_. And after reading in more detail react-hook-forms documentation I saw that:
[defaultValues are cached](https://react-hook-form.com/docs/useform#:~:text=defaultValues%20are%20cached)

This got me thinking to try reproduce this issue using useState, and I get the same result:

```
'use client';
import { useEffect, useState } from 'react';

export default function FormTest() {
  const [title, setTitle] = useState<string>()

  useEffect(() => {
    setTitle('qwe')
  }, [])

  return <Input defaultValue={title} label='Title' variant='bordered'} />
}
```
![image](https://github.com/nextui-org/nextui/assets/106311891/16cf64c2-6a00-44b3-ae26-965efccf428c)

**Comment by WorldOfMaze** [comment]
@RAK-MANIAK, thanks for the feedback.  I changed the Input to `defaultValue={selectedItem && selectedItem.description}`.  This seems to wok properly `selectedValue` is not null with the label about the input as well as when `selectedValue` is null in which case the label is inside of the input.

A small hack, but it works.

Thanks again for the suggestion.

**Comment by gabor-boros** [comment]
@FullmetalBober I've facing the exact same issue. Try using a React Form Hook`Controller`: https://react-hook-form.com/get-started#IntegratingwithUIlibraries

```typescript
'use client';

import { TTestSchema } from '@/schemas/test';
import { useForm, Controller } from 'react-hook-form';
import { Input } from '@nextui-org/input';

export default function FormTest() {
  const { control } = useForm<TTestSchema>({ defaultValues: { title: 'TEST' } });

  return (
    <form>
      <Controller
        name="title" 
        control={control}
        render={({ field }) => <Input {...field} label='Title' variant='bordered' />}
      /> 
    </form>
  );
}
```

**Comment by FullmetalBober** [comment]
@gabor-boros  Oh man, indeed, I forgot about the Controller, it finally works 🎉
Thanks for you reply😁

**Comment by gabor-boros** [comment]
I'm glad I could help 😇
