### ISSUE TITLE
[BUG] - SelectItem & ListBoxItem extendVariants -> Error: type.getCollectionNode is not a function

### ISSUE THREAD

**Issue by jarmo-jaaskelainen-crasman** [nextui-org/nextui#1761]
### NextUI Version

^2.1.13

### Describe the bug

Bug is already pretty well described in Discord: https://discord.com/channels/856545348885676062/1161994818424156211

### Steps to Reproduce the Bug or Issue

1. extendVariants of SelectItem:

```
import {
  Select as NextUISelect,
  SelectItem as NextUISelectItem,
  SelectProps as NextUISelectProps,
  SelectItemProps as NextUISelectItemProps,
  extendVariants,
} from "@nextui-org/react"

interface SelectItemProps extends NextUISelectItemProps {
  variantType?: "primary"
}

const SelectItemComponent = extendVariants(NextUISelectItem, {
  variants: {
    variantType: {
      primary: {
        description: '',
        base: '',
        title: '',
        wrapper: '',
        selectedIcon: '',
        shortcut: '',
      }
    }
  },
  defaultVariants: {
    variantType: "primary",
  }
})

export function SelectItem(props:SelectItemProps) {
  return (
    <SelectItemComponent { ...props } />
  )
}
```

There will be error: 
`Error: type.getCollectionNode is not a function`

### Expected behavior

Should work just like in button, pagination etc. components.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @jarmo-jaaskelainen-crasman this issue is a bit complex to fix due to the nature of [react-aria collections](https://react-spectrum.adobe.com/react-stately/collections.html),in the meantime you can use this workaround. 

```ts
SelectItemComponent.getCollectionNode = SelectItem.getCollectionNode
```

https://codesandbox.io/p/sandbox/elegant-hopper-35hyw2?file=%2FApp.jsx%3A24%2C1-25%2C1&utm_medium=sandpack

This is valid for all collection-based components: Select, DropdownMenu, Table etc...
