### ISSUE TITLE
[BUG] - Progress does't have color

### ISSUE THREAD

**Issue by ImRLopezAG** [nextui-org/nextui#1933]
### NextUI Version

2.0.24

### Describe the bug

When I use the progress component with the property isStriped the color appears as default it also happens on the doc page

how it supposed to be
![image](https://github.com/nextui-org/nextui/assets/88790737/3d76a8a6-4178-4633-91bf-7e86c0096909)

### Steps to Reproduce the Bug or Issue

1. Update to latest version
2. Use the Progress component with the property isStriped
3. Add the property color how you prefer it

### Expected behavior

Your component will look like if it has the default color
![image](https://github.com/nextui-org/nextui/assets/88790737/5aa3db4e-4d07-4dea-8d8c-60da4bb2688a)
 

### Screenshots or Videos

how it looks like

![image](https://github.com/nextui-org/nextui/assets/88790737/493a44b7-d618-4706-99fc-6cf050b10c2e)
![image](https://github.com/nextui-org/nextui/assets/88790737/fce4d36a-8d76-41d8-abd9-7d7e54be08d9)

### Operating System Version

Windows

### Browser

Edge

**Comment by KoJem9Ka** [comment]
The problem is still not solved in NextUI 2.4.8. Whatever color I set together with isStriped prop, progress bar is always gray and current value not recognizable with the background. It doesn't matter if theme is dark or white.

<details><summary>It appears directly on the docs</summary>

![preview](https://github.com/user-attachments/assets/1854f09c-e105-4ed3-8476-691ab74f1716)
![code](https://github.com/user-attachments/assets/44c12d5e-55ff-4fe1-81b6-7f3bebd42208)

</details>

**Comment by ShrinidhiUpadhyaya** [comment]
Hi @wingkwong can i work on this?
