### ISSUE TITLE
[BUG] - Tabs component type error "Type 'Key' is not assignable to type 'Key | null | undefined'."

### ISSUE THREAD

**Issue by MeonisRP** [nextui-org/nextui#1938]
### NextUI Version

2.2.8

### Describe the bug

Seems like some type error

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-jfhwnj?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

open /app/page.tsx (Line 22)

### Expected behavior

I expect no type errors :)

### Screenshots or Videos

![Screenshot at Nov 09 15-41-56](https://github.com/nextui-org/nextui/assets/66072651/450b3b9a-37bb-4698-b956-49c1c81ec43b)

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @MeonisRP looks like the react-aria tabs key is different from the rest which uses `React.Key`, as a workaround while this is fixed, you can import the `Key` type from `'@react-types/shared';` instead of using the react one.

https://stackblitz.com/edit/stackblitz-starters-rtm2h5?file=app%2Fpage.tsx,node_modules%2F%40react-types%2Fshared%2Fsrc%2Fselection.d.ts
