### ISSUE TITLE
[BUG] - Autocomplete doesn't close when a open modal is open

### ISSUE THREAD

**Issue by daniel-esserweb** [nextui-org/nextui#1987]
### NextUI Version

2.2.9

### Describe the bug

If you place an autocomplete component inside a modal it does not close in any way unless you select an item

### Steps to Reproduce the Bug or Issue

Open a modal
Click the autocomplete
Click outside when autocomplete is open

### Expected behavior

It should allow clicking anywhere on the overlay to close the autocomplete menu without closing the modal

### Operating System Version

Windows

### Browser

Chrome

**Comment by tetslee** [comment]
Maybe you're looking for this prop: `allowsCustomValue={true}`
https://nextui.org/docs/components/autocomplete#autocomplete-props

**Comment by vinishanto** [comment]
I am also having the same issue, 
plus the tab animations are also not working within the Modal

**Comment by cmoscosoz** [comment]
> Maybe not exactly the same issue but I had a similar problem that was solved adding the prop `allowsCustomValue={true}` https://nextui.org/docs/components/autocomplete#autocomplete-props

That's a good temporary solution. the problem is I don't want the user to select a custom value on the autocomplete, but I can handle it with a custom validation for now.

**Comment by NiroopR1999** [comment]
> Maybe not exactly the same issue but I had a similar problem that was solved adding the prop `allowsCustomValue={true}` https://nextui.org/docs/components/autocomplete#autocomplete-props

This resolved my issue. Thanks

**Comment by adnan-smlatic** [comment]
This issue is still happening in 2.7.6 when using <AutoComplete> with a popover opaque or blur. 

The problem is by default Autocomplete doesn't block clicks outside the AutocompleteItems. 

So if you want to just close the Autocomplete but not click  on let's say a button under it, you have to enable popover backdrop. But if you do that it doesn't work properly and doesn't close the Autocomplete unless you add ```allowsCustomValue={true}```.

Which does not make any sense at all. I spent hours looking into this. How can this solve it??!? Regardless thank you @tetslee I love you
