### ISSUE TITLE
Navbar Link causing page the entire page to reload

### ISSUE THREAD

**Issue by Rahulg321** [nextui-org/nextui#2212]
### NextUI Version

2.2.9

### Describe the bug

When I use the Navbar and Link component from nextui it causes the entire page to reload. But when I use Link component from next then the page does not reload, but I lose the styles provided in the navbar

### Steps to Reproduce the Bug or Issue

1. Use the navbar component
2. try clicking on any link to see if the page reloads or not

### Expected behavior

As a user I expected it to not reload the page and work as a normal link component just like next navigation

### Operating System Version

Windows

### Browser

Chrome

**Comment by eduard-if** [comment]
Hi, this may not be a bug in case you have not set up the NextUIProvider. 
You should check out the [routing section](https://nextui.org/docs/guide/routing) in the NextUI docs. You need to set up a NextUIProvider for the router you are using so that the NextUI components know how to perform client side routing.
