### ISSUE TITLE
[BUG] - Bug when input type is file.

### ISSUE THREAD

**Issue by vikramsamak** [nextui-org/nextui#2311]
### NextUI Version

~~2.2.9~~ 2.4.1

### Describe the bug

When using the input component with file type, I observed that on the first click to choose a file, the selected file is logged as "undefined" in the console. However, on the second attempt, the correct file information is logged

### Steps to Reproduce the Bug or Issue

Click the "Choose File" button to open the file dialog.
On the first click, notice that the selected file is logged as "undefined" in the console.
On the second click, the correct file information is logged.

### Expected behavior

The file input value should be cleared consistently on each click to ensure that the correct file information is logged on the first attempt.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/95061742/e210cb3e-c389-49ec-99b6-469d68d7a86b

### Operating System Version

windows 11

### Browser

Edge

**Comment by AustinZhu** [comment]
Same here, any solutions?

**Comment by johnjjimenez** [comment]
I am experiencing the same issue. For now, I using a regular input element and styled it the same.

**Comment by Ishov** [comment]
Same issue in 2.2.10

**Comment by HustCoderHu** [comment]
same issue in v2.3.6

**Comment by idmontie** [comment]
This seems to be an issue since `value=""` is set on the `input` element that `NextUI` creates.  It looks like `value=""` is assumed to be the default which isn't true for inputs with `type=file`. In [use-input.ts](https://github.com/nextui-org/nextui/blob/canary/packages/components/input/src/use-input.ts#L140-L151), an empty string is always assumed to be the default value an input should be.

If I force `value` to be null, the file input works as expected:

```
<Input
    {...rest}
    // @ts-expect-error -- Known issue with NextUI's Input component
    defaultValue={null}
    multiple={allowMultiple}
    onChange={handleChange}
    type="file"
    // @ts-expect-error -- Known issue with NextUI's Input component
    value={null}
/>
```

There are some related tickets to this issue in the issue tracker:

- https://github.com/nextui-org/nextui/issues/2965
- https://github.com/nextui-org/nextui/issues/2397

**Comment by vikramsamak** [comment]
Thanks for fix.
