### ISSUE TITLE
Can't use a custom size on <Loading /> component

### ISSUE THREAD

**Issue by bruxo00** [nextui-org/nextui#247]
**Describe the bug**
In the docs it's stated that:
`Change the size of the entire Loading with the size property, you can also set a custom size in px.`

But if I pass a number the component, like `<Loading size={64} type="points" />`, it doesn't render anymore (it renders but the sizes of the elements are 0px, so I can't see it).

**Steps to reproduce**
Create an element `<Loading size={200} type="points" />`

**Expected behaviour**
The element size should be 200 px.

**Environment / Context**
Desktop
Windows 10 64 Bits
Opera 83.0.4254.27

**Additional info**
**@nextui-org/react:** 1.0.2-beta.3
**react:** 17.0.2

**Comment by jrgarciadev** [comment]
Hey @bruxo00 thank you for reporting it,  it's a documentation mistake, we will update it as soon as possible since is not possible to pass a custom `integer` size to the loaders we remove that feature to avoid multiples issues, here a workaround for doing that -> https://codesandbox.io/s/great-montalcini-cyj39?file=/src/App.js

**Comment by bruxo00** [comment]
Thanks, will implement it based on your example 👍

**Comment by jrgarciadev** [comment]
Hey @bruxo00 we have already fixed the `Loading` docs https://nextui.org/docs/components/loading#sizes, I'm going to close this issue 👍🏻
