### ISSUE TITLE
[BUG] - NavbarMenuToggle component's Hamburger Icon not visible 

### ISSUE THREAD

**Issue by Dev-Code24** [nextui-org/nextui#2604]
### NextUI Version

2.2.10

### Describe the bug

The hamburger icon which should be visible in the mobile view, is not visible, but it is getting rendered and is actually functional too. 
According to me, it's just the background color not being defined properly for the::after and::before pseudo-elements 

### Steps to Reproduce the Bug or Issue

1. Go to [controlled-menu in Navbar](https://nextui.org/docs/components/navbar#controlled-menu)
2. Copy the code after installing @nextui-org/react and framer-motion and proper setup.
3. Paste the code in src/app/page.tsx and then npm run dev.
4. Upon resizing your browser window you will be able to see the logo getting centered after reaching a window-size, but you will not see any hamburger icon. Even though the icon is not visible, you will still be able to click on it and use to change the isMenuOpen state and also see the NavbarMenuItems

### Expected behavior

As a user I expected to see a Hamburger Icon visible to me

### Screenshots or Videos

This is what it looks now.

https://github.com/nextui-org/nextui/assets/97425135/8d3f274d-94f1-4969-b364-a3ea0890bf94

Steps I followed to make it visible:
I added background color to the ::after and ::before elements
<img width="1474" alt="Untitled" src="https://github.com/nextui-org/nextui/assets/97425135/77349d6f-500b-4bc1-bf4f-40d2436e4157">

<img width="238" alt="image" src="https://github.com/nextui-org/nextui/assets/97425135/91e689aa-ad9d-4a38-b53f-eba041981b70">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by ronakonline** [comment]
in tailwind.config.ts file add variable called "content"

```
 theme: {
    colors: {
      current: "#000000",
      primary: "#DD6043",
      info: "#FFFFFF",
      radiant: "#E2F6FC",
      blueSky: "#48B7D6",
    },
    }
```

**Comment by CX330Blake** [comment]
I encountered the same problem, and I eventually solved it by using [this](https://hamburger-react.netlify.app/?fbclid=IwZXh0bgNhZW0CMTEAAR0RBPOVOzmseqgErPcAjClbcnNzaq000xzBZxeTBGsxmswaRFM47zhbc3U_aem_8OLArapD33TGExdA_pBkow) as its icon. FYI.

**Comment by alexdev006** [comment]
Hi, 
Maybe you can share your code ?
Works for me with this implementation :

`   
import { Menu } from "lucide-react";
import {
  Navbar,
  NavbarContent,
  NavbarItem,
  NavbarMenu,
  NavbarMenuItem,
  NavbarMenuToggle,
} from "@heroui/react";

{/* Toggle Menu for Mobile */}
<Navbar>
      <NavbarContent>
        <NavbarMenuToggle
          icon={<Menu />}
          aria-label="Menu"
          className="sm:hidden"
        />
      </NavbarContent>
<Navbar/>
`

**Comment by RobProductions** [comment]
Posting here because I had a very similar but slightly different issue - my NavbarMenuToggle was not showing up at all and inspecting the elements in Chrome showed that `::before` and `::after` were not even appearing underneath the generated span element:

<img width="664" height="457" alt="Image" src="https://github.com/user-attachments/assets/15fc83f0-d9fc-4b27-82fe-968ab2da8a22" />

I eventually figured out that this happens when Tailwind has not generated the CSS styles used by HeroUI properly, because when I insert class names into the "safelist" in Tailwind config, it does work properly. But using the safelist is not a good way of fixing this. Instead you'd think that Tailwind would be able to pick up code in `node_modules` when you follow the installation steps, but for whatever reason it's not in my project. I have both the legacy (Tailwind V3) config listing the HeroUI files in "content":

```
content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ...
    "./node_modules/@heroui/**/*.{js,ts,jsx,tsx}",
],
```

And I have the V4 global CSS using the `@source` keyword to include the HeroUI files along with the legacy config:

```
@import 'tailwindcss';
/* Note: You may need to change the path to fit your project structure */
@source '../../node_modules/@heroui/**/*.{js,ts,jsx,tsx}';
@custom-variant dark (&:is(.dark *));

@config '../../tailwind.config.js';
@custom-variant hover (&:hover);
```

And yet it still refuses to include HeroUI's class names when generating the CSS styles. I have already confirmed that removing the legacy config line still doesn't work. Removing the source line and relying only on the legacy config doesn't work. Adding the `@plugin '../hero.ts';` doesn't work (makes sense because the legacy config should handle that already). So I still don't know why Tailwind isn't picking it up. When I made a minimal reproduction project it did work correctly, so there must be some difference between that and my big project, but I have no clue what it could be. I'm still on the trail of this and will update here if I find an answer in case it helps someone dealing with the same thing.

**Comment by RobProductions** [comment]
Not exactly sure how my project got screwed up or why it's different than the minimal project, but it seems that Tailwind was having an issue finding the Navbar styles. I was able to get Tailwind to find the class names by using this (the entire HeroUI folder) as the source line instead of the recommended installation path:

```
@source '../../node_modules/@heroui/';
```

In fact, while it may be valid syntax, I don't see any sort of pattern matching examples on the [Tailwind documentation](https://tailwindcss.com/blog/tailwindcss-v4#automatic-content-detection), so it seems like this is the way you're supposed to include package files. Still not sure what exactly is wrong but at least this lets the icon show up and it fixes the the other navbar menu problems due to missing CSS classes.
