### ISSUE TITLE
[BUG] - Navbar mobile menu not closed after item is clicked

### ISSUE THREAD

**Issue by grigorzyapkov** [nextui-org/nextui#2736]
### NextUI Version

2.3.0

### Describe the bug

NavbarMenuItem doesn't close the menu after clicked.

```
<NavbarMenuItem>
      <Link
        onClick={() => {
          // do something here...
        }}
      >
         Label
      </Link>
    </NavbarMenuItem>
```

### Steps to Reproduce the Bug or Issue

1. Copy "With Menu" example from https://nextui.org/docs/components/navbar#with-menu
2. Add the following item
```
<NavbarMenuItem>
      <Link
        onClick={() => {
          // do something here...
        }}
      >
         Label
      </Link>
    </NavbarMenuItem>
```
4. Try to click on the item
5. Navbar is not closed automatically

### Expected behavior

Close navbar mobile menu after item is clicked.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
@grigorzyapkov As of now, clicking the menu item won't close the menu. You have to listen to router's changes and close the modal in a controlled way.

**Comment by grigorzyapkov** [comment]
@wingkwong 

Actually, the menu item does close the menu if `href` prop is provided. For example, the following will close the menu.

```
<NavbarMenuItem>
      <Link
        href="/some-url"
      >
         Label
      </Link>
    </NavbarMenuItem>
```

where, the following code won't close the menu.

```
<NavbarMenuItem>
      <Link
        onClick={() => {
          router.push("/some-url")
        }}
      >
         Label
      </Link>
    </NavbarMenuItem>
```

**Comment by nazrul-dev** [comment]
please solved

**Comment by wingkwong** [comment]
@nazrul-dev @grigorzyapkov please create a stackblitz project

**Comment by alvarolozano** [comment]
As in the previous comments, my links have the href prop, using the Link component from NextUI
![image](https://github.com/nextui-org/nextui/assets/10405074/c0653410-9538-4340-a813-84496ba527e0)

I added an "onPress" event to close the menu after clicking the link. It works correctly, but for the visitors using iOS Safari/Chrome, when they click the link, the menu closes, but it does not navigate to the corresponding page.
![image](https://github.com/nextui-org/nextui/assets/10405074/2a28ee0b-584b-4d9c-b055-208e4cc5556b)

**Comment by m-naeem66622** [comment]
## Solution (Fixed)
The following solution work well for me. Infact i had implemented Accordions in `<NavbarMenu />`. Still this solution work great in `<AccordionItem />`

### Important Steps to [Controlled NavbarMenu](https://nextui.org/docs/components/navbar#controlled-menu)
1. Create a state to control the open and close state of the navbar
2. Pass the state value `isMenuOpen` and state setter function `setIsMenuOpen` as a prop `isMenuOpen` and `onMenuOpenChange` respectively to `<Navbar />` 
3. Alter the state in a handle to `onClick` event of `<Link />` or `<Button/>` what ever you want to use

```jsx
const [isMenuOpen, setIsMenuOpen] = useState(false);

return (
    <Navbar
      isMenuOpen={isMenuOpen} // state value
      onMenuOpenChange={setIsMenuOpen} // state setter function
    >
      <NavbarMenuItem>
        <Link
          onClick={() => {
            setIsMenuOpen((prev) => !prev))
            // do something more here...
          }}
        >
           Label
        </Link>
      </NavbarMenuItem>
    </Navbar>
);
```

**Comment by zpao** [comment]
The most elegant solution right now, at least if you're doing straightforward links, seems to be what the NextUI website itself does:

https://github.com/nextui-org/nextui/blob/78d4216bff293ac6d673658716582caf76269de3/apps/docs/components/navbar.tsx#L63-L67

Effectively, still track open state, but rather than handling it on link clicks like others here suggest, just close it when the pathname (via Next's `usePathname`) changes. Note that the `react-hooks/exhaustive-deps` lint rule (if you're using it) is going to complain if you don't include `isMenuOpen` in the dependencies array. It's wrong - we don't want the effect to trigger when the state changes as it makes it impossible to open the menu. It sees `isMenuOpen` is different (now `true`) and immediately sets it to false.

FWIW I'm not sure if this is exactly what @wingkwong meant in https://github.com/nextui-org/nextui/issues/2736#issuecomment-2059411516 but they work on this project so I trust them here :)

All that said, I agree with the sentiment of the issue - in an ideal world the closing behavior is handled automatically in the component library. Needing to use `Link` directly here isn't ideal. IMO `NavbarMenuItem` should probably take an `href` prop, just like `DropdownItem` (which then also closes its menu on click)

**Comment by shawnmclean** [comment]
This should be added to the docs.

Just this will work and compliant with how to use hooks and the deps array:

```ts
  useEffect(() => {
    setIsMenuOpen(false);
  }, [pathname]);
```
