### ISSUE TITLE
[BUG] - Upgrading from 2.2.10 to 2.3.5 breaks input component errorMessage prop.

### ISSUE THREAD

**Issue by ArnoldVanN** [nextui-org/nextui#2835]
### NextUI Version

2.3.5

### Describe the bug

Using an input component with errorMessage set to a property or an errorMessages object:
`<Input name="name" type="text" label="Server Name" value={serverName} onChange={handleInputChange} onValueChange={setServerName} errorMessage={errorMessages.name} />
`
Whenever client side input validation fails and `errorMessage={errorMessages.name}` gets set, a div gets rendered but it doesnt contain the error message:
`<div data-slot="helper-wrapper" class="hidden group-data-[has-helper=true]:flex p-1 relative flex-col gap-1.5"></div>`

Even setting the error message explicitly results in the same bug

Reverting back to 2.2.10 fixed this issue.

### Steps to Reproduce the Bug or Issue

Create an input component
Set the errorMessage
Watch the wrapper element for the error message get rendered but not the error message itself.
This was reproducible on all routes and components for me.

### Expected behavior

see an error message displayed below the input field

### Operating System Version

WSL Ubuntu 20.04

### Browser

Opera

**Comment by IraiDevPersonal** [comment]
Is there any solution for the error?

The same thing happened to me when updating to version 2.3.5, all the components that have the errorMessage property no longer show the error message.

**Comment by wingkwong** [comment]
@ArnoldVanN @IraiDevPersonal By looking at the code, it seems now you need to set `isInvalid` to `true` where there is an error. See [here](https://storybook.nextui.org/?path=/story/components-input--is-invalid&globals=locale:en-US) for an example.

**Comment by remorses** [comment]
@wingkwong in my opinion isInvalid should be automatically be set to true if errorMessage isn't an empty string, otherwise the user has to set isInvalid manually when there is an error message, which is additional code that could be removed

**Comment by wingkwong** [comment]
@remorses `errorMessage` can also be set in a uncontrolled way, e.g.

```tsx
<Input {...args} errorMessage="Please enter a valid email address" />
```

With the logic you mentioned, you will see the following result. While in the real life case, it shouldn't be shown before any user's invalid input. Also `isInvalid` should be set based on the validation state, which should be controlled. In this case, we can cover both controlled and uncontrolled `errorMessage`.

<img width="318" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/0f3e7f70-7623-4661-ae9a-e1ebdbf43f78">

**Comment by alirezatayebinejad** [comment]
in the new update you must add isInvalid should be added to the inputs for the error message to work properly

**Comment by ArnoldVanN** [comment]
> @ArnoldVanN @IraiDevPersonal Just checked the code, now you need to set `isInvalid` to `true` where there is an error. I think the reason behind was to make both input and the error message `text-danger` together.
> 
> https://github.com/nextui-org/nextui/blob/1dacf52f305a410cbf59d067d1977024d982ad03/packages/components/input/src/input.tsx#L49-L55
> 
> You may also refer the [storybook](https://storybook.nextui.org/?path=/story/components-input--is-invalid&globals=locale:en-US) for an example.

Thanks!
Not sure how i feel about this change since i didnt really want or need the styling to change on invalid input. But i was able to use the classNames prop to get around this and maybe it's better this way for general use cases anyways.

**Comment by predragnikolic** [comment]
I think this is likely a regression, can we reopen this?

If `errorMessage=` is a truthy value,  I expect the component to behave as it did prior 2.3.5 
and that is to display the error message without me specifying `isInvalid`.

If this is not a regression, but rather an intentional choice, 
that should be communicated in the release notes to us devs.

**Comment by predragnikolic** [comment]
Also note,
I saw #2892 

The [docs](https://github.com/nextui-org/nextui/pull/2892/files#diff-690218c0f82a52b26423c2019d00e8419fa6503acf28fbd1b99f5be024680dcbR110) say that we now need `isInvalid`  in order to display the `errorMessage`:
```
You can combine the `isInvalid` and `errorMessage` properties to show an invalid input. `errorMessage` is only shown when `isInvalid` is set to `true`.
```

While the PR is merged and this is documented now
I still see that addressing that issue in this way is not the best for developers using nextui.

The reason why I consider this a breaking change is that the NextUI behaved differently before 2.3.5.
Previously nextUI didn't require `isInvalid` in order to show the `errorMessage` 
and now it does require `isInvalid` to show the `errorMessage`.

Which means that each dev now have to go through the entire project 
and add `isInvalid` checks everywhere: (which is not ideal)
<img width="791" alt="Screenshot 2024-04-29 at 14 49 10" src="https://github.com/nextui-org/nextui/assets/22029477/c8105576-9c1b-4a5e-9c9d-81afd1219149">
... 46 changed files bellow ...


It would help if this was mentioned in the release notes with a proper version bump. (not a patch version bump)
Because people need to update their code accordingly.

----

Ideally I would suggest keeping the old behavior.
If not, please just make sure to communicate this change to other people via release notes.

And try not to hurry with resolving issues,
take your time to make decisions which you think is best! :)

**Comment by remorses** [comment]
Can we restore the previous behaviour? Obviously if the errorMessage is defined the input is invalid

**Comment by ryo-manba** [comment]
Thank you for the detailed discussion on this issue.

We are currently working on supporting multiple types of validation, including native [HTML constraint validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation), custom validation, and real-time validation. Due to this, the requirements for displaying error messages have become more varied, and it is necessary to handle validation conditions separately from the `errorMessage`.

Thank you for your understanding and continued support.
