### ISSUE TITLE
Image & Avatar Component

### ISSUE THREAD

**Issue by jrgarciadev** [nextui-org/nextui#285]
### Discussed in https://github.com/nextui-org/nextui/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **devgossips** February 10, 2022</sup>
1. While researching I found a awkward result in Avatar component:
   `<Avatar src="" css={{ size: "$20" }} />`
 ![image](https://user-images.githubusercontent.com/70798495/153444523-ef7c7b63-b785-4fa2-8cc5-d26ccbf81969.png)
Please avoid the background color!
 But according the documentation it should show :
![image](https://user-images.githubusercontent.com/70798495/153444948-8000c3e8-75f8-4ed4-84ae-df966e5dbbfe.png)

2. `<Image src="/avatars/avatar-4.png"/>` what ever is the value of src it is showing a blank white placeholder !!

Please check is this really a bug or I made a mistake in code !
</div>

**Comment by wiksien** [comment]
I will fix that.

**Comment by jrgarciadev** [comment]
Great! @wiksien , I'm going to assign it to you

**Comment by wiksien** [comment]
@jrgarciadev While executing command "yarn build:nextui" I had an error pop up: "Error: ENOENT: no such file or directory, scandir 'C:\Users\wiste\Desktop\Github Stuff\nextui\packages\react\lib\esm'". I don't know how to proceed.

**Comment by jrgarciadev** [comment]
Hey @wiksien, It looks like Windows needs the folder `esm` to be created before saving the files there 🤔 , you could try creating it and then run `yarn build:nextui`

**Comment by wiksien** [comment]
@jrgarciadev It is weird, because when I do that it just assumes this folder doesn't exist and creates a new folder structure completely without it. Here is the whole message my CLI gave. 

`wiste@DESKTOP-II22GL2 MINGW64 ~/Desktop/Github Stuff/nextui (replaceplaceholder)
$ yarn build:nextui
yarn run v1.22.17
$ turbo run build --scope=@nextui-org/react --no-deps
• Packages in scope: @nextui-org/react
• Running build in 1 packages
@nextui-org/react:build: cache miss, executing fa940c38e788e3c5
@nextui-org/react:build: $ node ./scripts/build.js
@nextui-org/react:build: Building targets: all
@nextui-org/react:build: 
@nextui-org/react:build: Building: generating .d.ts
@nextui-org/react:build: Built: generating .d.ts
@nextui-org/react:build: Building: commonjs modules
@nextui-org/react:build: Building: es modules
@nextui-org/react:build: Building: browser distributable
@nextui-org/react:build: babel:
@nextui-org/react:build: babel:
@nextui-org/react:build:   C:\Users\wiste\Desktop\Github does not exist
@nextui-org/react:build:   Stuff\nextui\packages\react\src does not exist
@nextui-org/react:build:   Stuff\nextui\packages\react\lib\esm does not exist
@nextui-org/react:build:   C:\Users\wiste\Desktop\Github does not exist
@nextui-org/react:build:   Stuff\nextui\packages\react\src does not exist
@nextui-org/react:build:   Stuff\nextui\packages\react\lib\cjs does not exist
@nextui-org/react:build: error Command failed with exit code 2.
@nextui-org/react:build: error Command failed with exit code 2.
@nextui-org/react:build: Built: commonjs modules
@nextui-org/react:build: Built: es modules
@nextui-org/react:build: Built: browser distributable
@nextui-org/react:build: Building: Linking directories
@nextui-org/react:build: Error: ENOENT: no such file or directory, scandir 'C:\Users\wiste\Desktop\Github Stuff\nextui\packages\react\lib\esm'
@nextui-org/react:build: error Command failed with exit code 1.
@nextui-org/react:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@nextui-org/react:build: Error: command finished with error: exit status 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by wiksien** [comment]
@jrgarciadev It is weird, because when I do that it just assumes this folder doesn't exist and creates a new folder structure completely without it. Here is the whole message my CLI gave.

![obraz](https://user-images.githubusercontent.com/88692323/154168559-7a7eb8bb-79fe-4431-98b5-786ce286c837.png)

**Comment by jrgarciadev** [comment]
Hey @wiksien if you run `yarn sb` does it work?

**Comment by wiksien** [comment]
@jrgarciadev Nope, also doesn't work. It errors out saying that various files don't exist and that `Field 'browser' doesn't contain a valid alias configuration`

**Comment by algofishexe** [comment]
<img width="207" alt="Screen Shot 2022-02-17 at 1 41 12 AM" src="https://user-images.githubusercontent.com/96948441/154419902-aa647100-3526-45a4-ab28-c5a93550de7b.png">

Confirming a replica of this bug with source:

```js
<Avatar css={{ size: "$40" }} ... color="gradient" bordered />
```

**Comment by TianenPang** [comment]
Hey @wiksien, I believe it's because there are a space in the path `Github Stuff`, try to change a directory without spaces in the path, and then run `yarn build:nextui` should see output like this. ( just built it today on Windows


![build-nextui](https://user-images.githubusercontent.com/32772271/154637063-a4034a36-34cb-4cb3-ab46-a2b363db9067.png)

**Comment by devgossips** [comment]
I also agree with @TianenPang

**Comment by ayanonline** [comment]
Some time image is not showing, It just showing backgroud color 

![Screenshot from 2024-01-02 18-25-13](https://github.com/nextui-org/nextui/assets/90972070/23983188-0d06-42da-bebf-410f27792ca3)

![Screenshot from 2024-01-02 18-26-06](https://github.com/nextui-org/nextui/assets/90972070/27abbdb3-24de-4c01-9553-854f157d1bda)

**Comment by masnoonJunaid** [comment]
@ayanonline did you solve this issue? It works only with network images, not with local assets, please update if you make it work with local assets!

**Comment by wingkwong** [comment]
@masnoonJunaid I don't see problems with local assets. Are you putting the local path to `src` directly? If so, it will add a baseURL before the path. You need to import it and pass to `src`.

![image](https://github.com/nextui-org/nextui/assets/35857179/5d06d6f8-f36a-4871-afbe-b6c549316dfb)

**Comment by masnoonJunaid** [comment]
`import { Spacer, Divider, Avatar } from "@nextui-org/react"
import TeacherProfile from '../../assets/teacher_profile.png'
import StaffProfile from '../../assets/staff_profile.png'
import StudentProfile from '../../assets/student_profile.png'
import Image from "next/image"
`
this is how I am importing image, and I am trying to use it in avatar
` <Avatar
                  className="secondProfileImg"
                  src={TeacherProfile}
                  height={400}
                  width={400}
                  alt="university teacher"
                />`
                
                same things works for next image, but not with **Avatar**
                
                
<img width="753" alt="image" src="https://github.com/nextui-org/nextui/assets/36502601/65f0b399-a2a3-45c9-8067-e5e10b60b722">

**Comment by wingkwong** [comment]
Can you inspect the element to see if the path is valid? Also in your screenshot, is it true that you use next image for James Mink and Nextui avatar for the other two? If so, please create a new issue.

**Comment by masnoonJunaid** [comment]
![image](https://github.com/nextui-org/nextui/assets/36502601/35e73893-b15b-4084-8d8b-8da13e209a43)
first image is from 'next/image' and the second one from Avatar, In above picture I am using Image for first one, next two displayed by Avatar

**Comment by wingkwong** [comment]
`[object Object]` looks weird. I also tested with relative paths and it can render. Are you using the latest version?

**Comment by masnoonJunaid** [comment]
my next version is ` "next": "^14.1.4",`

**Comment by doomSDey** [comment]
Same issue

**Comment by ayanonline** [comment]
> @ayanonline did you solve this issue? It works only with network images, not with local assets, please update if you make it work with local assets!

I am also using network images but still it is not working some time

**Comment by wingkwong** [comment]
@ayanonline can you open a new issue with your example

**Comment by pmbednarczyk** [comment]
I have same issue.  Network images usually don't load properly.

**Comment by hazemm48** [comment]
> my next version is ` "next": "^14.1.4",`

I have fixed it by adding .src after the image variable.

It should be like this:

import profileImgPlaceholder from '@/app/assets/profile/profileImagePlaceholder.png';

<Avatar src={profileImgPlaceholder.src} />

**Comment by noFAYZ** [comment]
> `import { Spacer, Divider, Avatar } from "@nextui-org/react" import TeacherProfile from '../../assets/teacher_profile.png' import StaffProfile from '../../assets/staff_profile.png' import StudentProfile from '../../assets/student_profile.png' import Image from "next/image" ` this is how I am importing image, and I am trying to use it in avatar ` <Avatar className="secondProfileImg" src={TeacherProfile} height={400} width={400} alt="university teacher" />`
> 
> ```
>             same things works for next image, but not with **Avatar**
> ```
> 
> <img alt="image" width="753" src="https://private-user-images.githubusercontent.com/36502601/330688751-65f0b399-a2a3-45c9-8067-e5e10b60b722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTEyMDEsIm5iZiI6MTcyNDE1MDkwMSwicGF0aCI6Ii8zNjUwMjYwMS8zMzA2ODg3NTEtNjVmMGIzOTktYTJhMy00NWM5LTgwNjctZTVlMTBiNjBiNzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEwNDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NjkzMjViMDJiM2Y2MzE3MGZiNDU3MzJlMDNjOWMxYjM4ZjI4Nzk3ZmFiMWUyMDMwOGVkMWY5ZTQ1YTlhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DtnjYatMRfPePdNKU-dxKt3kXsssAWa0qIPeDqJvi5g">

looks like the opacity doesn't change when the image is loaded.

![Capture](https://github.com/user-attachments/assets/b3139955-0a7f-4bd1-bd54-9b5e09498441)

**Comment by gnomefin** [comment]
what happened with this issue, why does this closed? the merged PR wasn't fixing this issue, tho.
But his @pmbednarczyk solution works:
```
imgProps={{ referrerPolicy: "no-referrer"}}
```
Any network-related issues or CORS (Cross-Origin Resource Sharing) policies that might be preventing the image from loading.

**Comment by Mominadar** [comment]
For me, 
```
imgProps={{ referrerPolicy: "no-referrer"}}
```

did not work but this did: 
```
<Avatar classNames={{
                        img: "opacity-100"
                    }}  />
```

Version: 2.4.2

**Comment by RoguedBear** [comment]
I was also debugging this before coming across this issue

in my case passing the `next/image` Image component as the `ImgComponent` and using google profile picture url, the avatar was stuck in grey color despite the image being shown as loaded in network tab.

setting opacity class directly from @Mominadar's comment worked

**Comment by sirlucasm** [comment]
> For me,
> 
> ```
> imgProps={{ referrerPolicy: "no-referrer"}}
> ```
> 
> did not work but this did:
> 
> ```
> <Avatar classNames={{
>                         img: "opacity-100"
>                     }}  />
> ```
> 
> Version: 2.4.2

why is this like that? This work for me
