### ISSUE TITLE
[Feature Request] Make `NextUIProvider` RSC-compatible

### ISSUE THREAD

**Issue by steebchen** [nextui-org/nextui#2898]
### Is your feature request related to a problem? Please describe.

Following up on #849, RSCs work with NextUI, but only when you use 'use client'. That is totally valid for the individual components, but the biggest restriction of this is that the `NextUIProvider` _also_ uses client side rendering, which switches all children to client components. This means that wrapping NextUIProvider near to the root (like directly under the body tag), then I can't use server things such as fetching HTTP requests or querying a database in a page component.

### Describe the solution you'd like

I'm not sure if it's technically possible, but it would be awesome if the `NextUIProvider` component would be a react server component (or somehow be compatible with it). Then I can still do server stuff in my NextJS pages using RSCs. The individual components stay client components as they don't need to be RSCs as you will not be doing any server side things in those.

### Describe alternatives you've considered

Right now I'm not using `NextUIProvider` in the root, but rather I query my database first, and then wrap each page in my custom `Providers` (which adds `NextUIProvider`). This seems to work fine, but means that I have to do and think about this for each individual page.

**Comment by jrgarciadev** [comment]
Hey @steebchen 

Having a client component at the root of your application doesn't force all child components to also be client-side. Client components can render server components as children. You can find more details on this in the official Next.js documentation here: [Using Context Providers](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers).

We use the `use client;` directive in the `NextUIProvider` because it manages a context internally, which is not supported by server components. This is by design and aligns with the current capabilities of server components.

Additionally, NextUI includes components that are server-compatible and don't require client-side rendering, such as:

[Kbd](https://nextui.org/docs/components/kbd)
[Spacer](https://nextui.org/docs/components/spacer)
[Badge](https://nextui.org/docs/components/badge)
[Code](https://nextui.org/docs/components/code)
[Divider](https://nextui.org/docs/components/divider)

**Comment by steebchen** [comment]
Ohh I see, guess I do not actually fully understand RSCs yet. That's great news, thanks for the quick clarification.
