### ISSUE TITLE
Wrong cursor position in the live editor

### ISSUE THREAD

**Issue by piall** [nextui-org/nextui#29]
**Describe the bug**
Currently, the cursor position is not aligning with the line where it should be.

**Steps to reproduce**
1. Go to any page where a live editor is available. (Suppose https://nextui.org/docs/components/checkbox)
2. Click on the live editor window

**Expected behaviour**
The cursor position should align with the clicked line

**Screenshots**
![Screenshot from 2021-09-13 01-52-25](https://user-images.githubusercontent.com/43095489/133000957-717bb121-02ca-4001-86a4-0cb4ce9d0f99.png)

**Environment / Context**
- All

**Comment**
I would like to work on that issue

**Comment by jrgarciadev** [comment]
Thank you for reporting it @piall, go ahead all yours, thanks for your help! 🙋🏻‍♂️

**Comment by piall** [comment]
My pleasure :smiley: . Is there any pre-requisite of environment setup?

**Comment by jrgarciadev** [comment]
Just be sure you have yarn installed because the project has built over yarn workspaces and be sure you have a node version >=12.13.0

Steps to start the docs project, Execute in the root of the project:

1. `yarn` 
2. `yarn dev:docs`

You will find the source code of the docs in -> packages/docs

Let me know if you need any help

**Comment by piall** [comment]
Thank you :raised_hands:

**Comment by jrgarciadev** [comment]
Hi! @piall any updates about this? 🙌

**Comment by piall** [comment]
I am busy with other stuff currently. I couldn't start work. :sweat: . I will try to give time on it today.
