### ISSUE TITLE
[BUG] - Empty DatePicker doesn't accept 31 as day if no month is given.

### ISSUE THREAD

**Issue by jannikdresselhaus** [nextui-org/nextui#2913]
### NextUI Version

2.3.6

### Describe the bug

When there is a datepicker with no value, it is not possible to start with the 31st of the month when inputting via keyboard. Instead, you have to first input a month with 31 days.

For a locale with a day-month-year date format this is unexpected behaviour.

### Steps to Reproduce the Bug or Issue

Create a datepicker with no value and try to put in 31 as a day.

### Expected behavior

I expect to be able to put in 31 as a day. When I then try to input a month with less than 31 days, the day field should be reset to null.

### Screenshots or Videos

![Example](https://github.com/nextui-org/nextui/assets/46087675/0306a187-16da-400e-88f7-765f01a98b10)

### Operating System Version

macOS/Ubuntu

### Browser

Chrome

**Comment by ryo-manba** [comment]
This is probably a bug in react-aria that we use in our implementation. This is because there is always a date under the hood, even when the placeholder is displayed. 
See: https://github.com/adobe/react-spectrum/issues/3256

The default is today's date, but you can also set it using the placeholderValue property.
````tsx
import {CalendarDate} from '@internationalized/date';

<DatePicker
  label="Birth date"
  placeholderValue={new CalendarDate(2020, 12, 1)}
/>
```
