### ISSUE TITLE
[BUG] - DatePicker - the calendar is truncated - wrong width

### ISSUE THREAD

**Issue by DanielMarkowski** [nextui-org/nextui#2917]
### NextUI Version

2.3.6

### Describe the bug

The calendar in the date picker or date range picker is truncated and does not show the last day column. It looks like the width is wrongly calculated and instead of 256 (default) the calendar size is 204px. If I manually change the inner div width in Chrome dev tools to 256 it looks ok. 

If I use the calendarWidth prop to set a different value then the inner div is still calculated to be 204px

### Steps to Reproduce the Bug or Issue

Use the minimal version of the Date picker or date range picker
example: 
`<DatePicker label={"Test Date picker"} />`

### Expected behavior

The calendar should be fully rendered. 

### Screenshots or Videos

![dp-width-1](https://github.com/nextui-org/nextui/assets/164039055/c30eb496-6f72-4450-ab2e-77c530445d08)
![dp-width-2](https://github.com/nextui-org/nextui/assets/164039055/baceb4bc-a182-4f92-b686-f2922faa4881)
![dp-width-3](https://github.com/nextui-org/nextui/assets/164039055/8c53e809-1ae3-405d-a3df-242129c2fb2f)

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Not able to reproduce the issue. (macOS with Chrome also) 

<img width="1264" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/7decea28-6e5d-4155-8a43-76408bfcd318">

**Comment by DanielMarkowski** [comment]
There must be some kind of listener which calculates this inner div width. I did nesty test to force change of this inner div with jquery after the calendar shows up like this

`setTimeout(() => {
     const divs = $('div[data-slot="calendar"]').children();
     if(divs.length > 2) {
	  $(divs[1]).width(256);
    }
}, 500);`

But after this code execution, the value was recalculated to 206 px ¯\_(ツ)_/¯
<img width="827" alt="image" src="https://github.com/nextui-org/nextui/assets/164039055/d0dbc38a-2ce3-4e8e-bd1b-a9f184980eda">

**Comment by DanielMarkowski** [comment]
After digging a bit in nextui code, for me it looks like this inner div width calculation is controlled by ResizablePanel which uses useMeasure and ResizeObserver so the problem might be with size of the nested content div. So the whole situation looks like this **class="w-[var(--calendar-width)]"** was not properly evaluated because dev tools show the size of 204x274 of the content div.

<img width="970" alt="image" src="https://github.com/nextui-org/nextui/assets/164039055/39f7b476-e059-4f7a-8773-6a20c041d31b">

**Comment by DanielMarkowski** [comment]
I did another nesty test with setting up the width size of this "content" div and the div wrapper calculated properly

`
setTimeout(() => {
	const divs = $('div[data-slot="calendar"]').children();
	if(divs.length > 2) {
		$($(divs[1]).children()[0]).width(256);
	}
}, 100);
`
<img width="657" alt="image" src="https://github.com/nextui-org/nextui/assets/164039055/7f911415-f6c0-4ab5-9982-259aacb75245">

So the question is why tailwind is not properly evaluating this expression _w-[var(--calendar-width)]_ Any ideas?

**Comment by wingkwong** [comment]
Are you able to reproduce the issue in [this example](https://storybook.nextui.org/?path=/story/components-datepicker--default&globals=locale:en-US)? Or can you provide a stackblitz link for us to investigate?

**Comment by christo9090** [comment]
I have the same issue as well. Cuts off right at Friday. You can hack a fix like this with tailwind for the time being:

` <DatePicker
                classNames={{
                  calendarContent: 'min-w-[250px]',
                }} />
               `

**Comment by nguyennamduong** [comment]
I had this issue before.
Updating to the latest next-themes and/or react-aria worked for me.

**Comment by DanielMarkowski** [comment]
> Are you able to reproduce the issue in [this example](https://storybook.nextui.org/?path=/story/components-datepicker--default&globals=locale:en-US)? Or can you provide a stackblitz link for us to investigate?

Your example is showing properly. Following @nguyennamduong advice I upgraded next-themes and react-aria libraries to the latest versions but it did not solve the problem. 

The problem was solved after I upgraded framer-motion to the newest stable version (I had 10.16.4 before). Here is my library stack after all the updates

"next": "^14.1.1",
"next-themes": "^0.3.0",
"react-aria": "^3.33.0",
"tailwindcss": "3.4.3",
"@nextui-org/react": "^2.3.6",
"framer-motion": "11.1.7",

Thanks for your hints guys.

**Comment by wingkwong** [comment]
@DanielMarkowski oh ok. We also bumped `framer-motion` to v11 several releases ago.

**Comment by Zegoverno** [comment]
Still facing this bug with the packages updated.

For me adding this solved.

classNames={{
  calendar: 'min-w-[300px]'
}}

**Comment by pataratanan** [comment]
I got this problem as well with nextui calendar(DatePicker) and I did all above comments and suggestion. Nothing better, It's very weird because it's only occur on the UAT but my localhost seems fine. I updated almost everything in the .json to the latest version

Please help me solve this problem


![Screenshot 2567-08-14 at 09 47 35](https://github.com/user-attachments/assets/fd30de8d-1ac2-49be-afdd-b51bf023726d)

**Comment by c-mateo** [comment]
After trying the suggested solutions without success and testing different versions of HeroUI and its dependencies, I found that this issue occurs because the calendar’s width is fixed in pixels, while the inner text uses a relative font size. With default browser font settings, this is not noticeable. However, if the font size is increased, the text inside the calendar grows while the container remains fixed, causing parts of the calendar to be hidden.

There are two possible workarounds:

- **❌ Less flexible:** Set the HTML font size to `16px`, as [HeroUI](https://www.heroui.com/docs/components/calendar) does.

- **✔ Recommended:** Set the `calendarWidth` prop to a relative unit (e.g., `16em` or larger) so it scales properly with font size. Ideally, this should be the default behavior.

⚠ **Note for `DatePicker`:** Using em units might not work as expected if its container defines a different font size. In this case, using rem units produces better results. While the typings and [documentation](https://www.heroui.com/docs/components/date-picker#datepicker-props) state that `calendarWidth` only accepts numeric values, you can safely pass a string.

This has been confirmed to work with the latest versions.
