### ISSUE TITLE
[BUG] - Incompatibilities with newer Next.js canaries.

### ISSUE THREAD

**Issue by jimapl** [nextui-org/nextui#3021]
### NextUI Version

2.3.6

### Describe the bug

seems nextui is not working with the newer next.js canaries.

PopoverTrigger throws 

`"Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead."`

When any variable or children is present within, even a div. Only flat string are accepted
See no issues on this topic on Github atm. But expect this will be a massive dealbreaker for many
Works in 14.2.3, breaks from canary 66

![Scherm­afbeelding 2024-05-18 om 14 44 21](https://github.com/nextui-org/nextui/assets/44089428/136bd7fc-1d91-4bae-b3a5-6de311b0653b)

### Steps to Reproduce the Bug or Issue

Install latest nextjs canary, for example. 14.3.0-canary-70.

Use a popover, tooltip or any other portal components where children are objects or components.

### Expected behavior

It to work.

### Screenshots or Videos

![Scherm­afbeelding 2024-05-18 om 14 44 21](https://github.com/nextui-org/nextui/assets/44089428/caa8c2d5-38a3-4d9f-9b69-ea4d84068731)

### Operating System Version

Mac

### Browser

Chrome

**Comment by wingkwong** [comment]
The nextjs canary version requires react 19, which seems react-aria currently not support yet.

**Comment by amauryfischer** [comment]
yeah it's going on :
https://github.com/adobe/react-spectrum/pull/6437

**Comment by lostfutures** [comment]
react-spectrum just merged react 19 support

**Comment by lostfutures** [comment]
react-spectrum just merged react 19 support @wingkwong

**Comment by Minisaints** [comment]
I'm also experiencing this issue on the latest RC versions. I tracked my issue down to the Dropdown. Even using the example Dropdown code in the docs throws it.

` ⨯ Internal error: Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, props, _owner, _store}). If you meant to render a collection of children, use an array instead.`

 "@nextui-org/react": "^2.4.2",
  "react": "^19.0.0-rc-6fb39ec9e9-20240621",

**Comment by jimmailcamp** [comment]
Yeah, only when you return a plain string it works. Any objects throws this. 
also the case for tooltip/popover and any other component basicly.

**Comment by zerosoul** [comment]
any progress?

**Comment by vcctm** [comment]
up, any progress?

**Comment by wingkwong** [comment]
This issue has been marked as on hold. Here's the reasons.

1. NextJS 15 RC is using React 19 RC. Just FYI, recently there is a heated discussion about sibling components of suspended components causing performance issue. React team is planning to hold the release until they find the good fix.
2. react-spectrum has merged the related changes to support 19 but it hasn't been GA yet. We're still waiting for the release and we're **NOT** using a nightly version in our production release. We may consider to have a beta version (probably would be introduced after v2.5.0) so that you may optionally use it at your own risk.
3. Please note that supporting a major version upgrade is not just like bumping the version and everything will be working fine. There's lots of things to evaluate and consider. It could potentially break lots of logics and require effort to fix them. Please be patient and eventually we will support it, when everything is ready. 

I'm going to lock this conversation and will unlock it once we got some actual updates.

**Comment by wingkwong** [comment]
Currently supported in canary branch. Will target to release in 2.6.0. However, `framer-motion` hasn't released a stable version supporting react 19. One could override it with their alpha version.
