### ISSUE TITLE
Hex color strings allowed as direct props to link component 

### ISSUE THREAD

**Issue by jeelmakani** [nextui-org/nextui#304]
**Is your iteration request related to a problem?**
I need to be able to pass hex color strings as a prop to [link](https://nextui.org/docs/components/link) component 

**Describe the solution you'd like**
be able to pass hex color strings as a prop to [link](https://nextui.org/docs/components/link) component 

**Additional context**
Nothing

**Comment by Dhananjay-JSR** [comment]
here's the alternative way to pass hex color string into your link component

`<Link color href="#" css={{color: "#F96123"}}>THIS</Link>`

**Comment by jrgarciadev** [comment]
Hey @jeelmakani the idea behind NextUI and Stitches is to have a system design with predefined colors like `primary`, `secondary`, `link` etc, `NextUI` provides you with a way to modify those colors (https://nextui.org/docs/theme/customize-theme), that's why is not allowed to pass color strings instead you can use the `css` property as @Dhananjay-JSR mentioned for setting a custom color that you haven't defined in your `theme`
