### ISSUE TITLE
[Feature Request] Optimize AutoCompelete and Select components for large options. 

### ISSUE THREAD

**Issue by I-am-abdulazeez** [nextui-org/nextui#3047]
### Is your feature request related to a problem? Please describe.

First of all, nice library. I would say I have been following this library before its birth. I love the way `Vuesax` looks, so I was looking for something similar in the React world. You came at the right time. Nice work once again!

I have about `270,000+` options while using the `Autocomplete` component. Before you call me crazy, I'm only fetching the data when the user inputs a search query. Again, I'm not crazy. I'm using debounce from `Lodash`, and every good stuff that will make it work right. But, it is too slow. i mean very slow.

### Describe the solution you'd like

I would suggest making it efficient like `react-select`, I tried using it, but I did not get how to merge both. I wanted to have the functionalities of it + `next UI` beautiful Autocomplete component.

I don't mind if someone could provide an example

### Describe alternatives you've considered

`react-select`

**Comment by matteogilioli** [comment]
> does [this](https://nextui.org/docs/components/autocomplete#asynchronous-filtering) help?

Async is still slow because it makes API calls, you could implement virtualization with react-window somehow.

**Comment by LPSebi** [comment]
any updates?

**Comment by radu-torro** [comment]
i'm also interested

**Comment by pacoorozco** [comment]
I'm interested too... I'm generating an AutoComplete with 1200 items and it's very, very slow.

**Comment by vinroger** [comment]
Hi @wingkwong, I am interested to take this and improve the time complexity for searching the options. Can I take this? Thank you!

**Comment by wingkwong** [comment]
@vinroger assigned. please research a bit if react-aria has done something for the optimisation first.

**Comment by vinroger** [comment]
@wingkwong 

Upon profiling, I discovered that the delay in the autocomplete feature is primarily due to the rendering of the DOM for the React component list, as there is currently no virtualization implemented. 
*The actual search processing takes minimal time (approximately 2-3 ms).


![image](https://github.com/user-attachments/assets/7cb57291-d654-443f-9d71-7517f8cad174)
^ Multiple react dom function call (creating 1000 list items) -> amounting to total ~26 seconds for 1000 items

![image](https://github.com/user-attachments/assets/46e13b85-2419-4bb8-b2ed-8e434782f1e4)
^ One call to search the autocomplete result -> 2-3ms

Hence, I am considering to add list virtualization to fix this.

For the list virtualization, I discovered that the virtualizer component in react-aria is currently marked as unstable, as indicated in their Storybook documentation: 

https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/stories/ListBox.stories.tsx

Would you be open to considering the use of an alternative, stable virtualizer library, such as react-window?

Thank you! looking forward to your response :)

**Comment by LPSebi** [comment]
If a third party library is considered, please view tanstack virtual as a viable option

https://tanstack.com/virtual/latest

**Comment by vinroger** [comment]
Hi @wingkwong, let me know if I could proceed with `react-window` [Link to npm package](https://www.npmjs.com/package/react-window), 

if yes I will submit the PR soon :)
Thanks!

**Comment by wingkwong** [comment]
> For the list virtualization, I discovered that the virtualizer component in react-aria is currently marked as unstable,

do you know why they marked as unstable? and what does it mean exactly? 

> Would you be open to considering the use of an alternative, stable virtualizer library, such as react-window?

I think better stick to RA implementation instead of third party one.

**Comment by vinroger** [comment]
Hi @wingkwong,

Based on their release note on July 2024, the virtualizer component is "unstable" and they mentioned that it is not intended for public use. 

Link to RA release notes: https://react-spectrum.adobe.com/releases/2024-07-22.html

_"We are also working on bringing virtualization support to React Aria Components, which is available as an unstable API in this version."_

Here is a screenshot from the webpage:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/4e88c251-a111-42f0-8cf2-90827151ee84">

There is no mention of virtualizer update ever since. July 2024 was their second latest release.

With this being said, should we still go with the virtualizer from react-aria, or should we consider alternative library?

After deciding on this, I will submit the PR as soon as possible.

Thank you - appreciate your help! :)

**Comment by vinroger** [comment]
Hi @wingkwong, I have opened a PR for this issue :) 

https://github.com/nextui-org/nextui/pull/4000

**Comment by matteogilioli** [comment]
@jrgarciadev Is the Select component also works with isVirtualized after this PR? From the docs it doesn't look like
