### ISSUE TITLE
[BUG] - use-client error in client components

### ISSUE THREAD

**Issue by abhinandan-verma** [nextui-org/nextui#3383]
### NextUI Version

2.4.2

### Describe the bug

The code of non-server rendered components like navbar, input, model etc do not have **use client** on their top in docs.
So whenever someone uses their code from docs.
The first error he gets is to use **use client** at top

### Steps to Reproduce the Bug or Issue

Use any code given in docs of any non-server rendered component 

### Expected behavior

**use client** should be present at top of  their code.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by Sarthak0085** [comment]
I don't think there is any requirement of using **"use client"** in their components code because **"use client"** is required mostly when the person use useState, useEffect or any other hooks and in the code there is not any use in their components. But if  the person is using the hooks in the nextjs code then that components must be of **"use client"** and their parent component must be of **"use client"** also.

**Comment by wingkwong** [comment]
To supplement a bit, we perviously revised rsc so that most components no longer require `use client` directive. However, there is some exceptions. For example, if you are using collection-based components, then it is required. For this part, we're waiting for RA team to release the new version so that we could work on it. Also if you are using client hook, such as `useDisclosure`, then you need that directive. Therefore, it really depends.

I'll close this issue first. It's better to handle by our team members.

**Comment by MiloWang2048** [comment]
> To supplement a bit, we perviously revised rsc so that most components no longer require `use client` directive. However, there is some exceptions. For example, if you are using collection-based components, then it is required. For this part, we're waiting for RA team to release the new version so that we could work on it. Also if you are using client hook, such as `useDisclosure`, then you need that directive. Therefore, it really depends.
> 
> I'll close this issue first. It's better to handle by our team members.

We do really need a comprehensive list shows which component/hook is not working directly in rsc. Please add it to doc site, mark it as an unresolved problem, and link to relative issue so we can track it and update the library when it closed.
