### ISSUE TITLE
[BUG] - Select component onChange not triggered when there are more than 300 SelectItems

### ISSUE THREAD

**Issue by x-o1d** [nextui-org/nextui#3455]
### NextUI Version

2.1.8

### Describe the bug

If a Select component is created with 300 SelectItems everything works as expected. onChange is triggered when an item is selected.
But if the Select component is created with 301 (or more) SelectItems onChange is not triggered when an item is selected.

### Steps to Reproduce the Bug or Issue

Create a Select component
Log the onChange event
Dynamically add 301 or more SelectItems
Click on a Select item, onChange is not triggered

### Expected behavior

There are no documented limitations of the number of options. Select should work with any number of options.

### Operating System Version

Linux

### Browser

Firefox

**Comment by wingkwong** [comment]
1. please confirm if it is reproducible in the latest version
2. if not, please share a minimal reproducible environment like stackblitz.

**Comment by x-o1d** [comment]
Reproducible in the latest version.

Minimal reproducible environment: https://stackblitz.com/edit/vitejs-vite-qsmd9d?file=src%2FApp.tsx

**Comment by AnthonyPaulO** [comment]
This bug is due to a size check in hidden-select.tsx line 142, where for sizes <= 300 it renders a select element with a ref associated with it, but for larger sizes it renders an input element without a ref. This results in the domRef being null for sizes greater than 300, and if the domRef is null then the onChange doesn't get triggered because onChange requires props from the domRef to be passed into the onChange event, and since domRef is null then it doesn't call the onChange. This check occurs in use-select.ts line 252.

The question here is, how do we want to handle this?

**Comment by wingkwong** [comment]
The number 300 is referenced from RA hiddenSelect. The bug here, as you mentioned, is due to the absence of the domRef for such case. I've made some changes locally already. Just need some time to write the test and make the PR.
