### ISSUE TITLE
[BUG] - Inputs Components color, helperColor, status  

### ISSUE THREAD

**Issue by Feli02** [nextui-org/nextui#378]
### Describe the bug

When I want to assign a customize color, helpColor or status to any input I receive a message saying it cannot receive a string. It only allows me to pass any of the default values such as primary, secondary, success, warning, error.  But I want it to have a custom color.
Anyway, I don't know if it is okay, but the problem seems to be solved when I add to color, helpColor, and status in the input-props.d.ts file that they can receive string. This I have to do it also in the input-password.d.ts file. 
PD: See the photos below

### Steps to Reproduce the Bug or Issue

1. Create an Input Component
2. Add a customize color
3. You will see the error

### Expected behavior

Not see the error and the input change color

### Screenshots or Videos

<h3>Error</h3>
<img width="960" alt="2022-03-30 (1)" src="https://user-images.githubusercontent.com/65402578/160944884-51ec2a70-3e09-4159-b6ac-d9d816ec8c8d.png">
<h3>Original file</h3>
<img width="960" alt="2022-03-30 (3)" src="https://user-images.githubusercontent.com/65402578/160945001-5a0280af-f1bb-49d7-9f88-2aabcf8cf580.png">
<h3>My solution</h3>
<img width="960" alt="2022-03-30 (2)" src="https://user-images.githubusercontent.com/65402578/160944892-a1dcf8b3-2efa-4a0d-ae33-30df9a127d37.png">

### Operating System Version

Windows

### Browser

Chrome

**Comment by Feli02** [comment]
I'm still needing some help with this

**Comment by jrgarciadev** [comment]
Hey @Feli02 sorry for the delay, NextUI allows you to customize the default theme colors such as primary, secondary, success, error, etc.. 

https://nextui.org/docs/theme/customize-theme
https://nextui.org/docs/theme/default-theme

NextUI doesn't support a custom color name through "color", "helperColor", "status" etc because the idea is to have a System Desing with strict colors although you can customize anything you want using the `css` prop or `styled` function

https://nextui.org/docs/theme/override-styles
