### ISSUE TITLE
[BUG] - Button

### ISSUE THREAD

**Issue by LeTam206** [nextui-org/nextui#3819]
### NextUI Version

2.4.8

### Describe the bug

When I use button with color="danger" and variant="ghost", I see a bug at the color of button

### Steps to Reproduce the Bug or Issue

Use button with color="danger" and variant="ghost"

### Expected behavior

Color of the button when no hover must be white color

### Operating System Version

Windows

### Browser

Chrome

**Comment by AnYiEE** [comment]
You can use `0.0.0-canary-20240915130349` instead of 2.4.8 until updating to 2.5.0, or temporarily add an additional class like [I did](https://github.com/AnYiEE/touhou-mystia-izakaya-assistant/blob/v1.2.13/app/(pages)/preferences/dataManager.tsx#L303) (both solutions are from the developer's opinion).

**Comment by wingkwong** [comment]
Fixed in https://github.com/nextui-org/nextui/pull/3764. you may use canary version at this moment or add `data-[hover=true]:!text-danger-foreground`.
