### ISSUE TITLE
Table cell should allowed copy of data

### ISSUE THREAD

**Issue by milindsingh** [nextui-org/nextui#389]
### Is your feature request related to a problem? Please describe.

Table row doesnt allow selecting content and copy.
It would very using if we can do so.

### Describe the solution you'd like

Render a tabld and try select content of one cell using cursor.

### Describe alternatives you've considered

Tried row selection, but it does the purpose of copying one cell content.

**Comment by razvanilin** [comment]
Is there a workaround for this? I tried using `user-select: text` on the cells, rows, and the entire table and can't make it work. I also inspected the page trying to find what's disabling the user selection but I can't find anything

**Comment by jrgarciadev** [comment]
Hey guys 👋🏼, thank you for reporting it, I just sent a PR with the solution https://github.com/nextui-org/nextui/pull/716, however, it will work only for non-selectable tables because as the `react-aria` team has mentioned [here](https://github.com/adobe/react-spectrum/issues/2585#issuecomment-1007829321) things start to get tricky when you introduce drag/drop, selection, virtualizers, non-text components inside cells.

The PR will be available in the next version `v11`, in the meantime you can use this [example](https://codesandbox.io/s/brave-glade-h78ge?file=/src/App.js) to make it work
