### ISSUE TITLE
[BUG] - UI component can't work on latest version

### ISSUE THREAD

**Issue by TIMMLOPK** [nextui-org/nextui#394]
### Describe the bug

When I update to 1.0.7,the UI compotent can't click.I am sure the problem not appear in 1.0.3

### Your Example Website or App

https://meme-maker-sec.vercel.app/

### Steps to Reproduce the Bug or Issue

1.Go to the web
2.The button and switch can't click

### Expected behavior

The component can work

### Operating System Version

Windows

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @TIMMLOPK it works for me 🤔 

https://user-images.githubusercontent.com/30373425/162197316-1ff76787-06dc-4651-9a5a-0a95c1a70b28.mov

**Comment by TIMMLOPK** [comment]
> 
I rolled back when you saw.I create version , it has issues now

**Comment by TIMMLOPK** [comment]
![image](https://user-images.githubusercontent.com/72869479/162664175-f4f28eaf-54a7-42a1-901d-e5e11b48d39c.png)
I find this issues also appear in nextui docs theme toggle button ,I think this issues is `usetheme` as the button should display sunicon when  `isDark=true`.The button can't click too

**Comment by TIMMLOPK** [comment]
@jrgarciadev Any progress of this ? I noticed `1.0.6-beta5` or after version will appear this issue

**Comment by TIMMLOPK** [comment]
Issues solved in `1.0.0-beta.6`

**Comment by JuanQuiro** [comment]
I am getting errors when using a component that uses Card and modals, the problem is giving me useMemo= 

Component =
```
import React from "react";
import { Card, CardHeader, CardBody, Image } from "@nextui-org/react";
import { useStoreGifs } from "../zustand/store";
import { useFetchData } from "../hooks/useGifExamplesRandom";
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Button,
  useDisclosure,
} from "@nextui-org/react";
export default function App() {
  const { CopyGifs, Types } = useStoreGifs();
  const { isOpen, onOpen, onOpenChange } = useDisclosure();
  const { data, isError, isLoading } = useFetchData();
  if (isLoading) return <Card className="py-4 mt-5">Cargando</Card>;
  if (isError) return <Card className="py-4 mt-5">Error</Card>;

  return (
    <>
      <Card isPressable onPress={onOpen} className="py-4 mt-5">
        <CardHeader className="pb-0 pt-2 px-4 flex-col items-start">
          <p className="text-tiny uppercase font-bold">{Types} #1</p>
          <small className="text-default-500">Texto = {CopyGifs}</small>
          <h4 className="font-bold text-large">{data?.data.data[0].title}</h4>
        </CardHeader>
        <CardBody className="overflow-visible py-2">
          <Image
            alt="Card background"
            className="object-cover rounded-xl"
            src={`${data?.data.data[0].images.original.url}`}
            width={270}
          />
        </CardBody>
      </Card>
      <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">
                {data.data.data[0].title}
              </ModalHeader>
              <ModalBody>
                <p>
                  Slug Gifs={" "}
                  <span className="text-green-800">
                    {data.data.data[0].slug}
                  </span>
                </p>
                <p>
                  Bitly Url ={" "}
                  <span className="uppercase text-green-800">
                    {data.data.data[0].bitly_gif_url}
                  </span>
                </p>
                <p>
                  Ranking ={" "}
                  <span className="uppercase text-green-800">
                    {data.data.data[0].rating}
                  </span>
                </p>

                <p>
                  Avatar ={" "}
                  <div className="mx-auto">
                    <Image
                      alt="Card background"
                      src={`${data?.data.data[0].user.avatar_url}`}
                      width={270}
                    />
                  </div>
                </p>
              </ModalBody>
              <ModalFooter>
                <Button color="danger" variant="light" onPress={onClose}>
                  Cerrar
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </>
  );
}
```

Visuals
![chrome-capture-2023-7-26](https://github.com/nextui-org/nextui/assets/54697159/9a3afd22-ef90-4739-94b4-7d1ec4aec436)


Error 
Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [true] at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:36987:7 at App (http://localhost:5173/src/components/CardResults.tsx?t=1693024787673:18:33) at GifsComponent (http://localhost:5173/src/main.tsx?t=1693021849272:25:26) at div at div at main at div at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11802:32) at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11769:9) at $f57aed4a881a3485$export$bf688221f59024e5 at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:5989:9) at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:12153:25) at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/chunk-IDHYU5OE.js?v=289ef9fd:2701:3) at App

%cWarning: The final argument passed to color: rgba(250, 123, 130, 0.75) changed size between renders. The order and size of this array must remain constant. Previous: useMemo Incoming: [][true] at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:36987:7 at App (http://localhost:5173/src/components/CardResults.tsx?t=1693024787673:18:33) at GifsComponent (http://localhost:5173/src/main.tsx?t=1693021849272:25:26) at div at div at main at div at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11802:32) at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11769:9) at $f57aed4a881a3485$export$bf688221f59024e5 at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:5989:9) at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:12153:25) at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/chunk-IDHYU5OE.js?v=289ef9fd:2701:3) at App

**Comment by TIMMLOPK** [comment]
> I am getting errors when using a component that uses Card and modals, the problem is giving me useMemo=
> 
> Component =
> 
> ```
> import React from "react";
> import { Card, CardHeader, CardBody, Image } from "@nextui-org/react";
> import { useStoreGifs } from "../zustand/store";
> import { useFetchData } from "../hooks/useGifExamplesRandom";
> import {
>   Modal,
>   ModalContent,
>   ModalHeader,
>   ModalBody,
>   ModalFooter,
>   Button,
>   useDisclosure,
> } from "@nextui-org/react";
> export default function App() {
>   const { CopyGifs, Types } = useStoreGifs();
>   const { isOpen, onOpen, onOpenChange } = useDisclosure();
>   const { data, isError, isLoading } = useFetchData();
>   if (isLoading) return <Card className="py-4 mt-5">Cargando</Card>;
>   if (isError) return <Card className="py-4 mt-5">Error</Card>;
> 
>   return (
>     <>
>       <Card isPressable onPress={onOpen} className="py-4 mt-5">
>         <CardHeader className="pb-0 pt-2 px-4 flex-col items-start">
>           <p className="text-tiny uppercase font-bold">{Types} #1</p>
>           <small className="text-default-500">Texto = {CopyGifs}</small>
>           <h4 className="font-bold text-large">{data?.data.data[0].title}</h4>
>         </CardHeader>
>         <CardBody className="overflow-visible py-2">
>           <Image
>             alt="Card background"
>             className="object-cover rounded-xl"
>             src={`${data?.data.data[0].images.original.url}`}
>             width={270}
>           />
>         </CardBody>
>       </Card>
>       <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
>         <ModalContent>
>           {(onClose) => (
>             <>
>               <ModalHeader className="flex flex-col gap-1">
>                 {data.data.data[0].title}
>               </ModalHeader>
>               <ModalBody>
>                 <p>
>                   Slug Gifs={" "}
>                   <span className="text-green-800">
>                     {data.data.data[0].slug}
>                   </span>
>                 </p>
>                 <p>
>                   Bitly Url ={" "}
>                   <span className="uppercase text-green-800">
>                     {data.data.data[0].bitly_gif_url}
>                   </span>
>                 </p>
>                 <p>
>                   Ranking ={" "}
>                   <span className="uppercase text-green-800">
>                     {data.data.data[0].rating}
>                   </span>
>                 </p>
> 
>                 <p>
>                   Avatar ={" "}
>                   <div className="mx-auto">
>                     <Image
>                       alt="Card background"
>                       src={`${data?.data.data[0].user.avatar_url}`}
>                       width={270}
>                     />
>                   </div>
>                 </p>
>               </ModalBody>
>               <ModalFooter>
>                 <Button color="danger" variant="light" onPress={onClose}>
>                   Cerrar
>                 </Button>
>               </ModalFooter>
>             </>
>           )}
>         </ModalContent>
>       </Modal>
>     </>
>   );
> }
> ```
> 
> Visuals ![chrome-capture-2023-7-26](https://user-images.githubusercontent.com/54697159/263438852-9a3afd22-ef90-4739-94b4-7d1ec4aec436.gif)
> 
> Error Warning: The final argument passed to useMemo changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [true] at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:36987:7 at App (http://localhost:5173/src/components/CardResults.tsx?t=1693024787673:18:33) at GifsComponent (http://localhost:5173/src/main.tsx?t=1693021849272:25:26) at div at div at main at div at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11802:32) at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11769:9) at $f57aed4a881a3485$export$bf688221f59024e5 at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:5989:9) at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:12153:25) at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/chunk-IDHYU5OE.js?v=289ef9fd:2701:3) at App
> 
> %cWarning: The final argument passed to color: rgba(250, 123, 130, 0.75) changed size between renders. The order and size of this array must remain constant. Previous: useMemo Incoming: [][true] at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:36987:7 at App (http://localhost:5173/src/components/CardResults.tsx?t=1693024787673:18:33) at GifsComponent (http://localhost:5173/src/main.tsx?t=1693021849272:25:26) at div at div at main at div at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11802:32) at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:11769:9) at $f57aed4a881a3485$export$bf688221f59024e5 at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:5989:9) at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=289ef9fd:12153:25) at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/chunk-IDHYU5OE.js?v=289ef9fd:2701:3) at App

Seem not relates to the issue. You should open a new issue if you need.
