### ISSUE TITLE
[BUG] - Create Context error on importing any component

### ISSUE THREAD

**Issue by saurabhguptarock** [nextui-org/nextui#4153]
### NextUI Version

2.4.8

### Describe the bug

Whenever I import any component in page.tsx it gives an create context error.

NextJS - 15.0.3
@nextui-org/react - 2.4.8

### Steps to Reproduce the Bug or Issue

Just import any component and use it 

```
// app/providers.tsx
"use client";

import { NextUIProvider } from "@nextui-org/react";
import { useRouter } from "next/navigation";

export function Providers({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  return <NextUIProvider navigate={router.push}>{children}</NextUIProvider>;
}
```

### Expected behavior

There should be no error as we expect the component to work in SSR environment. 

### Screenshots or Videos

<img width="969" alt="Screenshot 2024-11-27 at 8 03 15 PM" src="https://github.com/user-attachments/assets/521048e7-2499-4740-ae44-fdd1f88282d2">

<img width="972" alt="Screenshot 2024-11-27 at 8 07 23 PM" src="https://github.com/user-attachments/assets/55c5dea1-7fc3-4780-bd70-d64f2ae28644">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment]
either add `use client` or use individual package

```tsx
import {Button} from "@nextui-org/button";
```

**Comment by saurabhguptarock** [comment]
why you closed this issue?

why can't we use @nextui-org/react it supposed to work as all the components use use client

**Comment by wingkwong** [comment]
The reason is that not all components are client components, so we cannot add use client to the main package (i.e. `@nextui-org/react`). Doing so would force all components to render on the client side when imported from the main package. However, in individual package (e.g. `@nextui-org/button`), we add the `use client` directive at build time so you can use it without specifying that. Therefore, there are two ways to resolve this problem - either add `use client` or use individual package.

**Comment by saurabhguptarock** [comment]
thanks
