### ISSUE TITLE
[BUG] - `SelectSection` heading cannot be `sticky` anymore

### ISSUE THREAD

**Issue by ethylon** [nextui-org/nextui#4335]
### NextUI Version

2.6.x

### Describe the bug

We used the example from [the documentation](https://nextui.org/docs/components/select#custom-sections-style) to have `sticky` heading in the `Select` dropdown. But this doesn't work anymore, even in the documentation you can see the heading disappearing on scroll.

### Your Example Website or App

https://nextui.org/docs/components/select#custom-sections-style

### Steps to Reproduce the Bug or Issue

Reproduce the example from the documentation.

### Expected behavior

Heading should be sticky when the `sticky` class or style is applied.

### Operating System Version

Windows

### Browser

Chrome

**Comment by HwangSeongYeol** [comment]
The same issue happens with the dropdown component of the Navbar component. I found this issue to work well in my local area but not in the deployed environment. Since the dependencies are written in `@nextui-org/react:"^2.4.8"`, the latest version of nextui was applied in the deployed environment and that was a shame. If someone has the same issue and needs to take action quickly, please fix and deploy the dependencies `@nextui-org/react:2.4.8`.
