### ISSUE TITLE
[BUG] - createContext only works in Client Components (With solution!)

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/nextui#4357]
### NextUI Version

2.6.8

### Describe the bug

When using --turbopack in NextJS 15 + React 19 you get the error: `createContext only works in Client Components. Add the "use client" directive at the top of the file to use it.`

![image](https://github.com/user-attachments/assets/8bb232b5-d75e-4f01-b302-9c4b36c330ed)

**!SOLUTION!**
_Point the import of the /skeleton to its component and not the general /react. This goes for all components not only skeleton_

### Your Example Website or App

https://codesandbox.io/p/devbox/nk4vk2?file=%2Fapp%2FSkeleton.tsx%3A2%2C52

### Steps to Reproduce the Bug or Issue

Start above codesandbox and run the application and it will fail with the error.
Uncomment the import with /skeleton and comment out the import with /react and it works

### Expected behavior

To be honest I don't know what the expected behavior should be. I always try to import from correct component directly. 

### Operating System Version

Window 11

### Browser

Chrome

**Comment by wingkwong** [comment]
The error is expected. Here's something you may need to know.

- NextJS by default uses server component.
- NextUI components  use React hooks. You cannot use a react hook in a server component unless you make it as a client component. You can do that by adding `use client` directive.
- You don't need to add `use client` directive in an individual package (e.g. `@nextui-org/skeleton`) because we add it to those required components internally. 
- Not all components are client components. Therefore, we cannot add `use client` to the global package `@nextui-org/react`. That's why when you import `Skeleton` from `@nextui-org/react`, you need to add it by yourself. Otherwise, you will get that error.

Therefore, you can either add `use client` if you want to use global package or just use an individual package.

**Comment by J4v4Scr1pt** [comment]
@wingkwong super thanks for the detailed explanation! 🙌 
I did not know the global package did not use the 'use client' directive, that explains a lot.

This worked before 2.6 for some reason though 😅. 
But anyhow I always try to import from the component folder because I like it better. 

Saw someone else had this issue also but no solution and it was closed, thought I would share this to help others.

If I have missed this then sorry, but maybe add this info in the docs? That if you use the global package in RSC's this error will appear. It was not easy to understand what caused it initially 😄
