### ISSUE TITLE
[BUG] - Setting tabs content with flex does not work

### ISSUE THREAD

**Issue by MYmyRedustY** [nextui-org/nextui#4374]
### NextUI Version

2.6.8

### Describe the bug

I wanted to set the Tabs title width to 1/3 of the parent element and the content to 2/3, so I added flex-1 to base classname and flex-2 to panel. The base works, but the panel doesn't seem to work. You can see flex-2 in the classname of the panel but not work in webpage

### Steps to Reproduce the Bug or Issue

Init nextui with nextui-cli and then use the code

```
import { Tabs, Tab } from "@nextui-org/react";
import React from "react";

class TABStest extends React.Component {

    render() {
        return <div className="min-h-screen">
            <Tabs
                isVertical={true}
                classNames={{
                    base: 'flex-1',
                    tabList: 'min-h-screen ',
                    panel: 'flex-2',
                }}
                fullWidth={true}>
                <Tab key="1" title="TAB1">
                    <div className="">
                        Content1
                    </div>
                </Tab>
                <Tab key="2" title="TAB2">
                    <div className="">
                        Content2
                    </div>
                </Tab>
                <Tab key="3" title="TAB3">
                    <div className="">
                        Content3
                    </div>
                </Tab>
                <Tab key="4" title="TAB4">
                    <div className="">
                        Content4
                    </div>
                </Tab>
            </Tabs>
        </div>

    }
}
export default TABStest
```

### Expected behavior

Set the content width and works

### Operating System Version

windows

### Browser

Chrome

**Comment by wingkwong** [comment]
This issue doesn't relate to NextUI but to Tailwindcss. Your approach is actually correct. The reason it didn't work is because `flex-2` is not a part of tailwindcss utilities (available options: `flex-1`, `flex-auto`, `flex-initial` and `flex-none`. The classname is there but you can see `flex` is not in Styles section in inspector. However, you can customise `flex-2` by adding the following to your taiwind.config.js.

```js
theme: {
  extend: {
    flex: {
      '2': '2 2 0%'
    }
  }
}
```

In this way, you should see the following

![image](https://github.com/user-attachments/assets/20c702ec-9974-4506-aa47-8dce33e1b0c0)
