### ISSUE TITLE
[BUG] - Tabs don't work when using server-side rendering

### ISSUE THREAD

**Issue by SinnerK0N** [nextui-org/nextui#4456]
### NextUI Version

2.6.10

### Describe the bug

When I try to use Tabs component with server-side rendering enabled I run into this error:

Error: Functions are not valid as a child of Client Components. This may happen if you return children instead of <children /> from render. Or maybe you meant to call this function rather than return it.
  <... items={[...]} children={function children}>
                              ^^^^^^^^^^^^^^^^^^^
    at stringify (<anonymous>) {
  digest: '2018778322'
}

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-sgr33mgn?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

1. Use Tabs component with server-side rendering enabled

### Expected behavior

I expected for it to be working the same like it does when you specify "use client";

### Operating System Version

Linux

### Browser

Firefox

**Comment by wingkwong** [comment]
There're few things you need to know.

- Nextjs by default uses server components. This allows you to automatically implement server rendering with no additional configuration.
- In order to use react hooks, you need to add `use client` directive (i.e. using client compoents)
- A client component cannot be run in server side.
- NextUI Tab component is a client component because behind the scene it is using react hooks.

Therefore, your expected behaviour is not possible and you have to use `use client` directive for Tab component. Moreover, instead of putting the fetch logic along with the component in the same file, a general approach is to define the fetch logic in page level (says `page.tsx` with `use server`), then pass it to the component (says `components/tabs` with `use client`).

**Comment by keul** [comment]
I understands the technical limitation, but IMHO if a component only run client side, it should be clearly reported in the heroui docs!
