### ISSUE TITLE
[BUG] - Text "variant" is not applied when as component

### ISSUE THREAD

**Issue by SalahAdDin** [nextui-org/nextui#470]
### Describe the bug

We are using **Text** to print text on the site and we are expecting it to work as [**Typography** from MUI](https://mui.com/material-ui/customization/typography/): when we pass a variant with a different component(["as" in **NextUI**](https://nextui.org/docs/components/text#text-props)), we are expecting to have a **html** tag with the variant styles.

Our code is as follows:
```jsx
<>
        <Card.Body as="main" css={{ textAlign: 'center' }}>
          <Text h2 as="p">
            You will be presented with 10 True or False questions.
          </Text>
          <Text h2 as="p">
            Will you score 100%?
          </Text>
        </Card.Body>
        <Spacer y={2} />
        <Card.Footer as="footer">
          <Button
            size="lg"
            onPress={handleOnBeginClick}
            css={{ margin: 'auto' }}
          >
            Begin
          </Button>
        </Card.Footer>
      </>
```

It is rendering a **p** tag with **p** style, instead of rendering it with **h2** styles.

It could be the same problem stated before in this [issue](https://github.com/nextui-org/nextui/issues/410).

### Steps to Reproduce the Bug or Issue

1. Run the project.
2. Look the elements on the site to check the styles are wrong.
3. Go to inspect.
4. Find the tag with wrong styles.

### Expected behavior

It should render a **p** tag with **h2** styles, same thing as [**Typography** from MUI](https://mui.com/material-ui/customization/typography/) works.

### Screenshots or Videos

![asReplacesWholeStyles](https://user-images.githubusercontent.com/5034215/168453653-b45bf31d-cb09-41ec-a368-7d813030bb25.png)

### Operating System Version

5.15.28-1 Manjaro Linux x86_64

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @SalahAdDin, the `as` prop on `Text` component overrides any `Text` variation like `h1, h2, h3...`, because under the hood `NextUI` takes those props (h1, h2, h3...) and it pass them through the `as` prop, I recommend you render `h1` (h2,h3..) as `h1` and not as `p`

```js
<Text h2>
 You will be presented with 10 True or False
</Text>
```

I'll consider adding those styles through `classNames` as `MUI` does instead of applying them globally 

If you still want to have an `MUI` similar implementation here's a custom component based on NextUI `Text`:
https://codesandbox.io/s/nextui-custom-text-as-mui-6r4exr?file=/App.js

Hope it helps you 🙌🏻
