### ISSUE TITLE
[BUG] - css prop (declared but never used)

### ISSUE THREAD

**Issue by Ddupasquier** [nextui-org/nextui#629]
### Describe the bug

In my react file I am attempting to import and then use the css prop to change the font color of this user icon. When I import the css prop my IDE yell at me for not having used the prop. Not 100% sure if this is actually a bug or if I'm just dumb and doing things wrong.
I've attempted to use the prop without the import as well.

Hoping someone can help me with this. Thanks!

```import React from 'react';
import PropTypes from 'prop-types';
import { css, User } from '@nextui-org/react';

function UserIcon({ src, name, size }) {
  return <User src={src} name={name} size={size} css={{ color: 'white' }} />;
}

export default UserIcon;

UserIcon.propTypes = {
  src: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  size: PropTypes.oneOf(['xs', 'sm', 'md', 'lg', 'xl']).isRequired,
};

### Your Example Website or App

Working in private repo

### Steps to Reproduce the Bug or Issue

Private repo

### Expected behavior

As stated in description

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Chrome

**Comment by nerdjfpb** [comment]
Hi @Ddupasquier 
`css prop (declared but never used)` - means importing something you are not using inside code.  

As you are using `css` here - `<User src={src} name={name} size={size} css={{ color: 'white' }} />`

Maybe you thought you needed to import `css` but actually you don't need to do it. Because `User` Component already comes with `css` props, so you can just pass your props here. 

Find out more here - https://nextui.org/docs/components/user (go to down on the props part)

I've also made an example if you feel confused - https://stackblitz.com/edit/nextjs-myyf2g?file=pages/index.js
