### ISSUE TITLE
[Feature Request] Contrast in light theme

### ISSUE THREAD

**Issue by Ryannnkl** [nextui-org/nextui#635]
### Is your feature request related to a problem? Please describe.

I admire the project and I think it is an amazing design font and few things need improvement in terms of design, for example the contrast in the secondary texts in the light theme

### Describe the solution you'd like

Maybe lowering the opacity of the menu would make the contrast more aligned:

### Describe alternatives you've considered

I thought about changing the secondary text color of the light theme but in other places this color is great

### Screenshots or Videos

> current

![Captura de tela de 2022-07-26 01-25-52](https://user-images.githubusercontent.com/48577990/180925575-a0bfe127-3a09-4c3d-b64d-a19283cd585d.png)

> new

![Captura de tela de 2022-07-26 01-48-12](https://user-images.githubusercontent.com/48577990/180925676-98f2d4c4-aac1-44bf-929f-d10b1ffb4f03.png)

**Comment by imchell** [comment]
I suggest that the color system of sidebar (menu) should adopt the one from search panel. The readability of search panel has improved a lot since a recent update. This move will also strengthen the consistency of the official site.

![search panel](https://us1.myximage.com/2022/07/27/61e2853dcd9ab3eb124cd0259fb9b350.png)
