### ISSUE TITLE
[Feature Request] Could we please get href support for dropdowns?

### ISSUE THREAD

**Issue by carsonfischl** [nextui-org/nextui#643]
I'm looking to do a site with dropdown menus for navigation. I'm currently nesting links in Dropdown.Item in the dropdown menu. I understand the key param can be used to link components but it's easier for beginners like me to use hrefs.

Ideally, something like
```
<Dropdown.Item href='/stuff'>
	Stuff
</Dropdown.Item>
```

I'm currently using something like:
```
<Dropdown.Item>
	<Link href="/stuff">
		Stuff
	</Link>
</Dropdown.Item>
```

**Comment by danielsimao** [comment]
To be honest and due respect, I don't agree with this. Its like asking to add href in a button, so you could achieve your end result with less syntax. Dropdowns contain a set of actions. If your action is to navigate, I think you should write exactly what you need, instead of adding features to a component that does not make sense to have them.

**Comment by carsonfischl** [comment]
Makes sense, I guess that's the proper way to do it, thanks :)

**Comment by razvanilin** [comment]
I do think it will be a good addition though. It could work like `<Button as={Link} href="..." />`.

I came across a use-case of using dropdowns in a landing page Navbar and not being able to add href for dropdowns hurts SEO. UX-wise, it's also bad because the user cannot open the link in a new tab or see the link before they click.

For example here it will be great to be able to treat dropdown items as link https://nextui.org/docs/components/navbar#with-dropdown-menu

**Comment by yeager-j** [comment]
> I do think it will be a good addition though. It could work like `<Button as={Link} href="..." />`.
> 
> I came across a use-case of using dropdowns in a landing page Navbar and not being able to add href for dropdowns hurts SEO. UX-wise, it's also bad because the user cannot open the link in a new tab or see the link before they click.
> 
> For example here it will be great to be able to treat dropdown items as link https://nextui.org/docs/components/navbar#with-dropdown-menu

Exactly. They *literally* list putting a Dropdown inside a Navbar in their own docs! But you can't *actually* make the DropdownItem link to anything out of the box.
