### ISSUE TITLE
[BUG] - Grid sizes shift

### ISSUE THREAD

**Issue by luixo** [nextui-org/nextui#644]
### Describe the bug

Hello,
Documentation states that `Grid` component accept various size props: `xs`, `sm`, `md`, `lg` and `xl`, they should be boolean.
Actually, they are number which define amount of 1/12 shares of the container.

The actual problem is that `xs` size actually applies on 650px-960px, not <= 650px as stated in docs. Also, there is no way to add styling for <= 650px layout.

The reason is this code: https://github.com/nextui-org/nextui/blob/main/packages/react/src/grid/grid-item.tsx#L112-L119

I'm not sure how that should be approached as I'm not familiar with repo's rules.
Let me know if I can make a PR on that, but I need a direction.

### Steps to Reproduce the Bug or Issue

1. Render `Grid` component with `xs={1}` and `sm={12}`
2. Fiddle around with screen size
3. On <= 650px as well as on 650px-960px there would be 1 share, over 960px there would be 12 shares.

### Expected behavior

Expected `xs` style to apply on <= 650px window size

### Operating System Version

macOS

### Browser

Chrome

**Comment by uki-strzelecki** [comment]
Hi, I hope to add a bit there. So according to my tests in this [sandbox](https://codesandbox.io/s/nextui-grid-sizing-2h4fyu?file=/App.js:494-552&resolutionWidth=644&resolutionHeight=675), it looks like `xs` sets up 0-960px range (which is also not what is expected). This can be seen in the lower grid of the sandbox. And as the original author mentioned, there is no way to set the ranges 0-650, 650-960 separately. I tried via `css`, however, this also does not seem to work properly, which can be seen in the upper grid presented in the sandbox.
First, it looks like setting `@xs` overwrites all other breakpoints setup - once this is set up, other breakpoints do not matter. 
Second, without setting up `@xs` I can get almost all ranges to work, except 650-960. For 0-650 `@xsMax` works well. 

It is irritating bug to be honest, I hope it will get fixed soon.

Please forgive me if I got something wrong.

**Comment by lhthang96** [comment]
Same problem, I inspected the class attributes and looks like the media query value of `sm` is set at 960px, `md` is set at 1280px.

<img width="682" alt="Screen Shot 2022-08-23 at 21 22 27" src="https://user-images.githubusercontent.com/47101905/186183779-8ccaccad-d2f1-404a-be1e-ba37534614e9.png">
<img width="682" alt="Screen Shot 2022-08-23 at 21 23 29" src="https://user-images.githubusercontent.com/47101905/186183793-aa0af60e-4e31-4923-877a-5d11f8f81d2c.png">

**Comment by jrgarciadev** [comment]
Hey guys @luixo @lhthang96 , the `@xs`, `@sm`, `@md`, `@lg` and `@xl` are the same as `@xsMin`, `@smMin`, etc..., which means the media query starts working after that specific breakpoint if you want a media query `<=650px` you should use `xsMax` and the same for the other media queries, here's the complete list https://nextui.org/docs/theme/media#media-queries

```
 // `bpMin` shortcuts 
  xs: `(min-width: 650px)`,
  sm: `(min-width: 960px)`,
  md: `(min-width: 1280px)`,
  lg: `(min-width: 1400px)`,
  xl: `(min-width: 1920px)`,

 // bpMin
  xsMin: `(min-width:650px)`,
  smMin: `(min-width: 960px)`,
  mdMin: `(min-width: 1280px)`,
  lgMin: `(min-width: 1400px)`,
  xlMin: `(min-width: 1920px)`,

 // bpMax
  xsMax: `(max-width: 650px)`,
  smMax: `(max-width: 960px)`,
  mdMax: `(max-width: 1280px)`,
  lgMax: `(max-width: 1400px)`,
  xlMax: `(max-width: 1920px)`,

```

Hope it clears the confussion

**Comment by luixo** [comment]
Is there a way to apply two types of rules "at least X px" and "at max X px"?
I implemented that manually in my project, but that's what `xsMin` / `xsMax` sounds for me.

**Comment by lhthang96** [comment]
Hi @jrgarciadev , thank you for your response.

In my case, I'm using the Grid component. Based on the documentation, we can make the layout responsively by defining the value of `xs`, `sm`, `md`, `lg` and `xl` (as similar to the way I have been using grid system of other UI libraries)

<img width="1440" alt="Screen Shot 2022-09-14 at 20 03 48" src="https://user-images.githubusercontent.com/47101905/190164284-c0b88600-9bbe-495a-8613-8c394fb51fea.png">

I made an example to illustrate my case in [this sandbox](https://codesandbox.io/s/sandpack-project-forked-01quhf?resolutionWidth=959&resolutionHeight=800&file=/App.js). I set the width value to 959px, it should meet the `sm` value and take the 50% width instead of 100%.

<img width="1440" alt="Screen Shot 2022-09-14 at 20 08 51" src="https://user-images.githubusercontent.com/47101905/190165248-8c6275f0-9219-4217-83f8-7dc32920bdd7.png">

You mentioned the `xsMax` query in the answer, but I cannot find a way to use it in the Grid component. Please let me know if I missed anything or got the wrong way in using the grid system.

**Comment by uki-strzelecki** [comment]
> Hey guys @luixo @lhthang96 , the `@xs`, `@sm`, `@md`, `@lg` and `@xl` are the same as `@xsMin`, `@smMin`, etc..., which means the media query starts working after that specific breakpoint if you want a media query `<=650px` you should use `xsMax` and the same for the other media queries, here's the complete list https://nextui.org/docs/theme/media#media-queries
> 
> ```
>  // `bpMin` shortcuts 
>   xs: `(min-width: 650px)`,
>   sm: `(min-width: 960px)`,
>   md: `(min-width: 1280px)`,
>   lg: `(min-width: 1400px)`,
>   xl: `(min-width: 1920px)`,
> 
>  // bpMin
>   xsMin: `(min-width:650px)`,
>   smMin: `(min-width: 960px)`,
>   mdMin: `(min-width: 1280px)`,
>   lgMin: `(min-width: 1400px)`,
>   xlMin: `(min-width: 1920px)`,
> 
>  // bpMax
>   xsMax: `(max-width: 650px)`,
>   smMax: `(max-width: 960px)`,
>   mdMax: `(max-width: 1280px)`,
>   lgMax: `(max-width: 1400px)`,
>   xlMax: `(max-width: 1920px)`,
> ```
> 
> Hope it clears the confussion

I am saddened to see this issue being neglected. The usage of those breakpoints as implemented is counter-intuitive for `xs`, especially because it does not match the official documentation. This has implications for the `Container` fluid prop not working as expected. This should be changed in the implementation, rather than asking everyone to set the `xsMax` styling... This is being mentioned over and over again in the form of new github issues or discord questions. It is a bad user experience. 

#757 
#754 
https://discord.com/channels/856545348885676062/886605174162989068/1020858780088541204
https://discord.com/channels/856545348885676062/886605174162989068/999132658296696833

I eventually managed to size my grid correctly, but it took me more than 2 hours to figure it out. Something that should take me a minute. [sandbox](https://codesandbox.io/s/nextui-grid-sizing-2h4fyu?file=/App.js&resolutionWidth=986&resolutionHeight=675).

Regards

**Comment by teith** [comment]
@uki-strzelecki please, update your sandbox
