### ISSUE TITLE
[BUG] - Button in input contentLeft handling input onClick events

### ISSUE THREAD

**Issue by notmedia** [nextui-org/nextui#656]
### Describe the bug

![input](https://user-images.githubusercontent.com/12993018/183300864-f11c80b8-5cb1-4edb-93c2-1f2e4827532b.gif)

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-98ti3q?file=/App.js

### Steps to Reproduce the Bug or Issue

use contentLeft with button like in docs

### Expected behavior

Button onClick handler triggers only when clicking on this button

### Operating System Version

macos

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Hey @notmedia thanks for reporting it, a workaround while we check & fix this bug is to use the `labelPlaceholder` prop to avoid the `hover` & `active` states, here's an example https://codesandbox.io/s/sandpack-project-forked-jubib0?file=/App.js

**Comment by vinit-churi** [comment]
Hello @jrgarciadev I would like to work on this, this is my first time working on a open source project, could you please assign me this bug

**Comment by R-J-dev** [comment]
The bug seems to occur when the StyledInputWrapper is rendered as an label. When rendering as a div, it looks like it works as it should. That specific code is located on this place: https://github.com/nextui-org/nextui/blob/69456c63aef0839f5075995db621ffd58dcf1ed6/packages/react/src/input/input.tsx#L256
![image](https://user-images.githubusercontent.com/115353861/230694604-e4417b5e-c585-4f87-84d4-6093f2e576f3.png)

I didn't had the time to figure out why using a label in this place results in this behavior, but maybe this helps a bit :)

**Comment by rukundob451** [comment]
@notmedia, is this still available?

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).
