### ISSUE TITLE
[BUG] - Input css background color not correct

### ISSUE THREAD

**Issue by rafeautie** [nextui-org/nextui#732]
### Describe the bug

Background color is not being set as one would expect.

Code:

```jsx
<Input
  clearable
  placeholder={t('search')}
  value={searchTerm}
  onChange={(e) => {
    setSearchTerm(e.currentTarget.value);
    setPage(1);
  }}
  css={{background: 'red'}}
/>
```

Visual Result:

![Screen Shot 2022-09-03 at 9 46 18 PM](https://user-images.githubusercontent.com/45886348/188297907-489dde80-35b4-4943-a851-1e20e504f10d.png)

### Steps to Reproduce the Bug or Issue

```jsx
<Input
  clearable
  placeholder={t('search')}
  value={searchTerm}
  onChange={(e) => {
    setSearchTerm(e.currentTarget.value);
    setPage(1);
  }}
  css={{background: 'red'}}
/>
```

### Expected behavior

The actual input area should have background of red, not the component behind it.

### Screenshots or Videos

![Screen Shot 2022-09-03 at 9 46 18 PM](https://user-images.githubusercontent.com/45886348/188297928-d0eebb6e-ea70-4384-94e9-57844a199eab.png)

![Screen Shot 2022-09-03 at 9 51 50 PM](https://user-images.githubusercontent.com/45886348/188297996-e96f39e0-c6bd-426f-820e-8786a689f1ef.png)

### Operating System Version

Mac OS

### Browser

Firefox

**Comment by jrgarciadev** [comment]
Hey @rafeautie due to the Input `css` is applied to the `container` and not to the `wrapper` you have to use a `variable` called `$$inputColor`, here's a codesandbox https://codesandbox.io/s/nextui-input-custom-background-5d83on?file=/App.js:0-154, we have an input migration to `react-aria` in our roadmap, we hope to make the customization a bit easier
