### ISSUE TITLE
[Feature Request] Made Radio `validationState` prop boolean

### ISSUE THREAD

**Issue by benmneb** [nextui-org/nextui#747]
### Is your feature request related to a problem? Please describe.

Not really a problem just seems strange that a boolean attribute (valid/invalid) needs the specific strings

### Describe the solution you'd like

the prop name changed to `isValid` and type changed to boolean

### Describe alternatives you've considered

it could accept either boolean or strings 'valid'/'invalid', though I don't see a use case for the strings that boolean cant do easier

**Comment by jrgarciadev** [comment]
Hey @benmneb thanks for the suggestions, however, that's not possible because we try to make the NextUI API as similar as possible to the [react-aria](https://react-spectrum.adobe.com/react-aria/) since it's the library we use for a11y and the components behaviours, here's you can find the  react-aria radio example: https://react-spectrum.adobe.com/react-aria/
