### ISSUE TITLE
[BUG] - Card shadow not working in latest Safari on Mac

### ISSUE THREAD

**Issue by gfazioli** [nextui-org/nextui#764]
### Describe the bug

The default variant shadow is not working on the latest Safari browser on Mac
<img width="537" alt="image" src="https://user-images.githubusercontent.com/432181/190119462-59f76d71-7692-491b-a389-b04f70bf2cf9.png">

everything seems fine on Chrome
<img width="522" alt="image" src="https://user-images.githubusercontent.com/432181/190119566-2c45aaaa-a71d-4173-ada4-3363110ca3bd.png">

### Steps to Reproduce the Bug or Issue

Go on the NextUI documentation https://nextui.org/docs/components/card

### Expected behavior

The card shadown should be visible

### Operating System Version

macOS

### Browser

Safari

**Comment by situ2001** [comment]
+1

I has the same bug on Safari 16.0

<img width="995" alt="image" src="https://user-images.githubusercontent.com/28241963/195271078-5a242917-e16b-4ed9-8651-c434839c459b.png">

This bug is shown on Safari mobile too.

![IMG_507E28D955AA-1](https://user-images.githubusercontent.com/28241963/195271447-4d527977-8b0a-4dcd-962f-f597fc992d5d.jpeg)

**Comment by ValiDraganescu** [comment]
Still happening, the cards look really bad in safari...
In Brave, the cards have a greyish color while on chrome they are white (light theme)
Also the switch button looks on in Brave with the dark theme.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2) and test this again.

All components have been written from scratch

https://nextui.org/docs/components/card
