### ISSUE TITLE
[Feature Request] usage in shadow dom | set root for stitches styles rendering 

### ISSUE THREAD

**Issue by shtelzerartem** [nextui-org/nextui#996]
### Is your feature request related to a problem? Please describe.

I want to be able to use nextui inside of a *shadow dom*, therefore it's needed to specify target element for stitches to render styles inside of it. 

In `createStitches` function there is a `root` property in order to do such things. ([Stitches code](https://github.com/stitchesjs/stitches/blob/2876c6fe835c4d499e87a8e53a5c586395e40358/packages/core/src/sheet.js#L28))
[Example of working code (Code Sandbox)](https://codesandbox.io/s/circular-json-reproduction-forked-gy01cx?file=/src/index.tsx)

### Describe the solution you'd like

Ideally, I would like to pass targetRef to the `<NextUIProvider/>`. 

```jsx
import { NextUIProvider } from '@nextui-org/react';
import root from 'react-shadow';

const DefaultApp = () => {
  const [ref, setRef] = useState(null);

  return (
      <root.div ref={setRef}>
        <NextUIProvider stitchesRoot={ref}>
          <App />
        </NextUIProvider>
      </root.div>
  );
};
```

### Describe alternatives you've considered

.

**Comment by he-la** [comment]
I agree that Shadow DOM support would be super helpful. Currently with the `stitches`-based styling engine, this seems pretty hard to pull off, since `stitchesRoot` needs to be available when `createStitches` is called. `createStitches` sets up the `styled` and other functions that are imported and used statically throughout the codebase.

I've tried wrapping the result of `createStitches` into the `ThemeContext` and only create the stitches lazily at runtime, transforming calls to `styled` etc into function components that resolve the actual `styled` implementation with `useContext(ThemeContext)` at render time. But this is only a partial solution since we also need to find a way to transform code like this into dynamically resolving the `keyframes` function:

```
const loading = keyframes({
  // [...]
});

// [...]

export const StyledImageSkeleton = styled("div", {
  // [...]
  animation: `${loading} 5s ease-in-out infinite`,
  // [...]
});
```

Note that the result of the `keyframes` call is converted into a string before `styled` is invoked, so we cannot use the same trick of wrapping `keyframes` into a react hook or function component behind the scenes.

--

Support for shadow DOM should be much easier to implement once NextUI on tailwindcss lands.

**Comment by jrgarciadev** [comment]
Closing this due to Stiches I no longer the styles engine

**Comment by djyde** [comment]
Render a Popover in shadow dom still not work.
